.TH "/Users/dimadem/Documents/GitHub/minishell/src/test/pipe Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/test/pipe Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpipe_test\&.c\fP"
.br
.in -1c
