.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfind_max_in_list\&.c\fP"
.br
.ti -1c
.RI "file \fBft_abs\&.c\fP"
.br
.ti -1c
.RI "file \fBft_atof\&.c\fP"
.br
.ti -1c
.RI "file \fBft_atoi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_atol\&.c\fP"
.br
.ti -1c
.RI "file \fBft_bzero\&.c\fP"
.br
.ti -1c
.RI "file \fBft_calloc\&.c\fP"
.br
.ti -1c
.RI "file \fBft_count_bits\&.c\fP"
.br
.ti -1c
.RI "file \fBft_exclude_delimiters\&.c\fP"
.br
.ti -1c
.RI "file \fBft_is_double\&.c\fP"
.br
.ti -1c
.RI "file \fBft_is_num\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isalnum\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isalpha\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isascii\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isdigit\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isprint\&.c\fP"
.br
.ti -1c
.RI "file \fBft_itoa\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memmove\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memset\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_char\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_int\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_percent\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_ptr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_str\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_unsigned_dec\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_unsigned_hex\&.c\fP"
.br
.ti -1c
.RI "file \fBft_printf\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putchar_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putendl_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putnbr_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putstr_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_split\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBft_striteri\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strjoin\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlcat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strmapi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strndup\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strnstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strrchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strtrim\&.c\fP"
.br
.ti -1c
.RI "file \fBft_substr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_tolower\&.c\fP"
.br
.ti -1c
.RI "file \fBft_toupper\&.c\fP"
.br
.ti -1c
.RI "file \fBisnum_from_str\&.c\fP"
.br
.ti -1c
.RI "file \fBlist_len_char\&.c\fP"
.br
.ti -1c
.RI "file \fBlist_len_str\&.c\fP"
.br
.ti -1c
.RI "file \fBlist_repeat_check_int\&.c\fP"
.br
.ti -1c
.RI "file \fBlist_repeat_check_str\&.c\fP"
.br
.in -1c
