.TH "/Users/dimadem/Documents/GitHub/minishell/src/execute Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/execute Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexecute\&.c\fP"
.br
.ti -1c
.RI "file \fButils_0\&.c\fP"
.br
.ti -1c
.RI "file \fButils_1\&.c\fP"
.br
.in -1c
