.TH "/Users/dimadem/Documents/GitHub/minishell/src/test Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBenv\fP"
.br
.ti -1c
.RI "directory \fBpipe\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBtest\&.h\fP"
.br
.in -1c
