.TH "/Users/dimadem/Documents/GitHub/minishell/src/parser Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/parser Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBheredoc\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_checker\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_checker_helpers\&.c\fP"
.br
.ti -1c
.RI "file \fBparser\&.c\fP"
.br
.ti -1c
.RI "file \fBparser_helpers\&.c\fP"
.br
.ti -1c
.RI "file \fBtokeniser\&.c\fP"
.br
.ti -1c
.RI "file \fBtokeniser_helpers\&.c\fP"
.br
.in -1c
