.TH "/Users/dimadem/Documents/GitHub/minishell/src/utils Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaux\&.c\fP"
.br
.ti -1c
.RI "file \fBclean_general\&.c\fP"
.br
.ti -1c
.RI "file \fBclean_tree\&.c\fP"
.br
.ti -1c
.RI "file \fBinitialise\&.c\fP"
.br
.ti -1c
.RI "file \fBprompt\&.c\fP"
.br
.ti -1c
.RI "file \fBstack_control\&.c\fP"
.br
.ti -1c
.RI "file \fBstack_control_2\&.c\fP"
.br
.ti -1c
.RI "file \fBvisualiser\&.c\fP"
.br
.in -1c
