.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection Directory Reference" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_get_next_line\&.c\fP"
.br
.ti -1c
.RI "file \fBheredoc\&.c\fP"
.br
.ti -1c
.RI "file \fBredirect_in\&.c\fP"
.br
.ti -1c
.RI "file \fBredirect_out\&.c\fP"
.br
.ti -1c
.RI "file \fButils\&.c\fP"
.br
.in -1c
