.TH "/Users/dimadem/Documents/GitHub/minishell/src/utils/clean_general.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/utils/clean_general.c
.SH SYNOPSIS
.br
.PP
\fR#include 'tokens\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_args\fP (char **args)"
.br
.ti -1c
.RI "void \fBfree_env_list\fP (\fBt_env\fP *env)"
.br
.ti -1c
.RI "void \fBfree_ms_data\fP (\fBt_ms_data\fP *data)"
.br
.ti -1c
.RI "void \fBloop_cleanup\fP (char *line, \fBt_token\fP *tokens, char *prompt, \fBt_ast\fP *tree)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_args (char ** args)"

.PP
Definition at line \fB16\fP of file \fBclean_general\&.c\fP\&.
.nf
17 {
18     int i;
19 
20     i = 0;
21     if (args)
22     {
23         while (args[i] != NULL)
24             free(args[i++]);
25         free(args);
26     }
27 }
.PP
.fi

.PP
Referenced by \fBfree_ms_data()\fP\&.
.SS "void free_env_list (\fBt_env\fP * env)"

.PP
Definition at line \fB29\fP of file \fBclean_general\&.c\fP\&.
.nf
30 {
31     t_env   *temp;
32 
33     while (env)
34     {
35         free(env\->key);
36         free(env\->value);
37         temp = env;
38         env = env\->next;
39         free(temp);
40     }
41 }
.PP
.fi

.PP
References \fBs_env::key\fP, \fBs_env::next\fP, and \fBs_env::value\fP\&.
.PP
Referenced by \fBfree_ms_data()\fP\&.
.SS "void free_ms_data (\fBt_ms_data\fP * data)"

.PP
Definition at line \fB43\fP of file \fBclean_general\&.c\fP\&.
.nf
44 {
45     if (data)
46     {
47         free_args(data\->args);
48         free_env_list(data\->envp);
49         free_env_list(data\->local_env);
50         free(data\->current_dir);
51         free(data);
52     }
53 }
.PP
.fi

.PP
References \fBs_ms_data::args\fP, \fBs_ms_data::current_dir\fP, \fBs_ms_data::envp\fP, \fBfree_args()\fP, \fBfree_env_list()\fP, and \fBs_ms_data::local_env\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void loop_cleanup (char * line, \fBt_token\fP * tokens, char * prompt, \fBt_ast\fP * tree)"

.PP
Definition at line \fB55\fP of file \fBclean_general\&.c\fP\&.
.nf
56 {
57     free(line);
58     free(prompt);
59     (void)tokens;
60     free_ast(tree);
61 }
.PP
.fi

.PP
References \fBfree_ast()\fP\&.
.PP
Referenced by \fBmain_loop()\fP, and \fBstatus_handler()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
