.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/find_max_in_list.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/find_max_in_list.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfind_max_in_list\fP (int a[], int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int find_max_in_list (int a[], int size)"

.PP
Definition at line \fB15\fP of file \fBfind_max_in_list\&.c\fP\&.
.nf
16 {
17     int max;
18     int i;
19 
20     max = INT_MIN;
21     i = 0;
22     while (i < size)
23     {
24         if (a[i] > max)
25             max = a[i];
26         i++;
27     }
28     return (max);
29 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
