.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_abs.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_abs.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_abs\fP (int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_abs (int n)"

.PP
Definition at line \fB15\fP of file \fBft_abs\&.c\fP\&.
.nf
16 {
17     if (n < 0)
18         return (\-n);
19     return (n);
20 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
