.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atol.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atol.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBft_atol\fP (const char *nptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "long ft_atol (const char * nptr)"

.PP
Definition at line \fB15\fP of file \fBft_atol\&.c\fP\&.
.nf
16 {
17     int     i;
18     int     neg;
19     long    res;
20 
21     i = 0;
22     neg = 1;
23     res = 0;
24     while (nptr[i] == '\\t' || nptr[i] == '\\v' || nptr[i] == '\\n'
25         || nptr[i] == '\\f' || nptr[i] == '\\r' || nptr[i] == ' ')
26         i++;
27     if (nptr[i] == '\-' || nptr[i] == '+')
28     {
29         if (nptr[i] == '\-')
30             neg = \-neg;
31         i++;
32     }
33     while (nptr[i] >= '0' && nptr[i] <= '9')
34         res = res * 10 + (nptr[i++] \- 48);
35     return (res * neg);
36 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
