.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atoi.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atoi.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_atoi\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_atoi (char * str)"

.PP
Definition at line \fB20\fP of file \fBft_atoi\&.c\fP\&.
.nf
21 {
22     int sign;
23     int num;
24     int i;
25 
26     sign = 1;
27     num = 0;
28     i = 0;
29     while (str[i] == ' ' || (str[i] >= '\\t' && str[i] <= '\\r'))
30         i++;
31     if (str[i] == '\-' || str[i] == '+')
32     {
33         if (str[i] == '\-')
34         {
35             sign = \-1;
36         }
37         i++;
38     }
39     while (str[i] >= '0' && str[i] <= '9')
40     {
41         num = num * 10 + (str[i] \- '0');
42         i++;
43     }
44     return (sign * num);
45 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
