.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atof.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_atof.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBft_atof\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double ft_atof (const char * str)"

.PP
Definition at line \fB15\fP of file \fBft_atof\&.c\fP\&.
.nf
16 {
17     double  res;
18     double  neg;
19     double  divider;
20     size_t  i;
21 
22     divider = 0\&.1;
23     res = 0;
24     neg = 1;
25     i = \-1;
26     while (str[i] < '0' || str[i] > '9')
27         if (str[i++] == '\-')
28             neg = \-1;
29     while (str[i] >= '0' && str[i] <= '9')
30     {
31         res = res * 10 + str[i++] \- 48;
32     }
33     if (str[i] == '\&.' || str[i] == ',')
34         i++;
35     while (str[i] >= '0' && str[i] <= '9')
36     {
37         res = res + (str[i] \- 48) * divider;
38         divider /= 10;
39         i++;
40     }
41     return (res * neg);
42 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
