.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_count_bits.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_count_bits.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_count_bits\fP (unsigned char current_char)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_count_bits (unsigned char current_char)"

.PP
Definition at line \fB13\fP of file \fBft_count_bits\&.c\fP\&.
.nf
14 {
15     int i;
16 
17     i = 0;
18     while (current_char)
19     {
20         i += 1;
21         current_char >>= 1;
22     }
23     return (i);
24 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
