.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_is_double.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_is_double.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_is_double\fP (const char *n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_is_double (const char * n)"

.PP
Definition at line \fB15\fP of file \fBft_is_double\&.c\fP\&.
.nf
16 {
17     unsigned long   i;
18     int             p;
19 
20     i = 0;
21     while (n[i] && (n[i] == '\\t' || n[i] == '\\n' || n[i] == '\\v'
22             || n[i] == '\\f' || n[i] == '\\r' || n[i] == ' '))
23         i++;
24     if (n[i] && (n[i] == '+' || n[i] == '\-'))
25         i++;
26     if (!n[i])
27         return (FALSE);
28     p = FALSE;
29     while (n[i])
30     {
31         if (!ft_isdigit(n[i]) && n[i] != '\&.' && n[i] != ',')
32             return (FALSE);
33         if ((n[i] == '\&.' || n[i] == ',') && p == TRUE)
34             return (FALSE);
35         if (n[i] == '\&.' || n[i] == ',')
36             p = TRUE;
37         i++;
38     }
39     return (TRUE);
40 }
.PP
.fi

.PP
References \fBFALSE\fP, \fBft_isdigit()\fP, and \fBTRUE\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
