.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_isdigit.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_isdigit.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isdigit\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_isdigit (int c)"

.PP
Definition at line \fB13\fP of file \fBft_isdigit\&.c\fP\&.
.nf
14 {
15     return (c >= '0' && c <= '9');
16 }
.PP
.fi

.PP
Referenced by \fBft_is_double()\fP, \fBft_is_num()\fP, and \fBft_isalnum()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
