.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_isalnum.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_isalnum.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isalnum\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_isalnum (int c)"

.PP
Definition at line \fB15\fP of file \fBft_isalnum\&.c\fP\&.
.nf
16 {
17     return (ft_isalpha(c) || ft_isdigit(c));
18 }
.PP
.fi

.PP
References \fBft_isalpha()\fP, and \fBft_isdigit()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
