.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_memmove.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_memmove.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memmove\fP (void *dest, const void *src, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_memmove (void * dest, const void * src, size_t n)"

.PP
Definition at line \fB24\fP of file \fBft_memmove\&.c\fP\&.
.nf
25 {
26     char            *d;
27     const char      *s;
28 
29     d = dest;
30     s = src;
31     if (d == s)
32         return (dest);
33     if (d < s || d >= s + n)
34         ft_memcpy(d, s, n);
35     else
36     {
37         d += n;
38         s += n;
39         while (n\-\-)
40             *(\-\-d) = *(\-\-s);
41     }
42     return (dest);
43 }
.PP
.fi

.PP
References \fBft_memcpy()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
