.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_memset.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_memset.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memset\fP (void *s, int c, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_memset (void * s, int c, size_t n)"

.PP
Definition at line \fB28\fP of file \fBft_memset\&.c\fP\&.
.nf
29 {
30     unsigned char   *ptr;
31 
32     ptr = s;
33     while (n\-\- > 0)
34         *ptr++ = (unsigned char)c;
35     return (s);
36 }
.PP
.fi

.PP
Referenced by \fBft_calloc()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
