.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_print_percent.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_print_percent.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_print_percent\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_print_percent (void )"

.PP
Definition at line \fB15\fP of file \fBft_print_percent\&.c\fP\&.
.nf
16 {
17     ft_putchar_fd('%', 1);
18     return (1);
19 }
.PP
.fi

.PP
References \fBft_putchar_fd()\fP\&.
.PP
Referenced by \fBft_formatssssss()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
