.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_print_int.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_print_int.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_print_int\fP (int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_print_int (int n)"

.PP
Definition at line \fB15\fP of file \fBft_print_int\&.c\fP\&.
.nf
16 {
17     int     len;
18     char    *num;
19 
20     num = ft_itoa(n);
21     len = ft_print_str(num);
22     free(num);
23     return (len);
24 }
.PP
.fi

.PP
References \fBft_itoa()\fP, and \fBft_print_str()\fP\&.
.PP
Referenced by \fBft_formatssssss()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
