.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_putnbr_fd.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_putnbr_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_putnbr_fd\fP (int n, int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_putnbr_fd (int n, int fd)"

.PP
Definition at line \fB20\fP of file \fBft_putnbr_fd\&.c\fP\&.
.nf
21 {
22     if (n == \-2147483648)
23         ft_putstr_fd("\-2147483648", fd);
24     else
25     {
26         if (n < 0)
27         {
28             ft_putchar_fd('\-', fd);
29             n = \-n;
30         }
31         if (n >= 10)
32             ft_putnbr_fd(n / 10, fd);
33         ft_putchar_fd((n % 10) + '0', fd);
34     }
35 }
.PP
.fi

.PP
References \fBft_putchar_fd()\fP, \fBft_putnbr_fd()\fP, and \fBft_putstr_fd()\fP\&.
.PP
Referenced by \fBft_putnbr_fd()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
