.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_putchar_fd.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_putchar_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_putchar_fd\fP (char c, int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_putchar_fd (char c, int fd)"

.PP
Definition at line \fB20\fP of file \fBft_putchar_fd\&.c\fP\&.
.nf
21 {
22     write(fd, &c, 1);
23 }
.PP
.fi

.PP
Referenced by \fBft_print_char()\fP, \fBft_print_percent()\fP, \fBft_print_str()\fP, \fBft_print_unsigned_hex()\fP, \fBft_put_hex()\fP, \fBft_put_ptr()\fP, \fBft_putendl_fd()\fP, and \fBft_putnbr_fd()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
