.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strlen.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strlen.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen\fP (const char *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlen (const char * s)"

.PP
Definition at line \fB15\fP of file \fBft_strlen\&.c\fP\&.
.nf
16 {
17     size_t  i;
18 
19     i = 0;
20     while (s[i])
21         i++;
22     return (i);
23 }
.PP
.fi

.PP
Referenced by \fBbuiltin_echo()\fP, \fBbuiltin_exit()\fP, \fBft_putstr_fd()\fP, \fBft_strdup()\fP, \fBft_strjoin()\fP, \fBft_strjoin_gnl()\fP, \fBft_strlcat()\fP, \fBft_strndup()\fP, \fBft_strnstr()\fP, \fBft_strstr()\fP, \fBft_strtrim()\fP, \fBft_substr()\fP, \fBgenerate_prompt()\fP, \fBgenerate_prompt_string()\fP, and \fBredirect_here_doc()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
