.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_substr.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_substr.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_substr\fP (char const *s, unsigned int start, size_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_substr (char const * s, unsigned int start, size_t len)"

.PP
Definition at line \fB27\fP of file \fBft_substr\&.c\fP\&.
.nf
28 {
29     char    *new_str;
30     size_t  i;
31     size_t  j;
32     size_t  size;
33 
34     size = ft_strlen(s) \- start;
35     if (start > ft_strlen(s))
36         size = 0;
37     else if (size > len)
38         size = len;
39     new_str = (char *)malloc(size + 1);
40     if (!s || !new_str)
41         return (0);
42     i = start;
43     j = 0;
44     while (i < ft_strlen(s) && j < len)
45         new_str[j++] = s[i++];
46     new_str[j] = '\\0';
47     return (new_str);
48 }
.PP
.fi

.PP
References \fBft_strlen()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
