.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strjoin.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strjoin.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strjoin\fP (char const *s1, char const *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strjoin (char const * s1, char const * s2)"

.PP
Definition at line \fB23\fP of file \fBft_strjoin\&.c\fP\&.
.nf
24 {
25     size_t  len;
26     char    *pt;
27     char    *result;
28 
29     if (!s1 || !s2)
30         return (NULL);
31     len = ft_strlen(s1) + ft_strlen (s2) + 1;
32     if (len == 0)
33         return (NULL);
34     pt = (char *)malloc(sizeof(char) * len);
35     if (!pt)
36         return (NULL);
37     result = pt;
38     while (*s1)
39         *pt++ = *s1++;
40     while (*s2)
41         *pt++ = *s2++;
42     *pt = '\\0';
43     return (result);
44 }
.PP
.fi

.PP
References \fBft_strlen()\fP\&.
.PP
Referenced by \fBenv_to_array()\fP, \fBft_find_path()\fP, \fBgenerate_prompt_string()\fP, and \fBheredoc()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
