.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strcmp.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strcmp.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_strcmp\fP (const char *s1, const char *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_strcmp (const char * s1, const char * s2)"

.PP
Definition at line \fB24\fP of file \fBft_strcmp\&.c\fP\&.
.nf
25 {
26     while (*s1 != '\\0' || *s2 != '\\0')
27     {
28         if (*s1 != *s2)
29             return ((unsigned char)*s1 \- (unsigned char)*s2);
30         s1++;
31         s2++;
32     }
33     return (0);
34 }
.PP
.fi

.PP
Referenced by \fBbuiltin_echo()\fP, \fBbuiltin_env()\fP, \fBcheck_heredoc()\fP, \fBexecute()\fP, \fBget_env()\fP, \fBheredoc()\fP, \fBopen_file()\fP, \fBredirect_here_doc()\fP, \fBset_env()\fP, \fBtest_get_env()\fP, \fBtest_set_env()\fP, \fBtest_unset_env()\fP, and \fBunset_env()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
