.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strndup.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strndup.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strndup\fP (const char *s, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strndup (const char * s, size_t n)"

.PP
Definition at line \fB23\fP of file \fBft_strndup\&.c\fP\&.
.nf
24 {
25     size_t  len;
26     char    *new;
27 
28     len = ft_strlen(s);
29     if (!s)
30         return (NULL);
31     new = malloc((n + 1) * sizeof(char));
32     if (!new)
33         return (NULL);
34     if (n > len)
35         n = len;
36     ft_strlcpy(new, s, n + 1);
37     return (new);
38 }
.PP
.fi

.PP
References \fBft_strlcpy()\fP, and \fBft_strlen()\fP\&.
.PP
Referenced by \fBappend_phrase_if_valid()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
