.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_toupper.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_toupper.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_toupper\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_toupper (int c)"

.PP
Definition at line \fB15\fP of file \fBft_toupper\&.c\fP\&.
.nf
16 {
17     if (c >= 'a' && c <= 'z')
18         return (c \- ('a' \- 'A'));
19     return (c);
20 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
