.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection/heredoc.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection/heredoc.c
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
