.TH "/Users/dimadem/Documents/GitHub/minishell/src/parser/heredoc.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/parser/heredoc.c
.SH SYNOPSIS
.br
.PP
\fR#include 'tokens\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcheck_heredoc\fP (char *line)"
.br
.ti -1c
.RI "char * \fBheredoc\fP (char *eof)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * check_heredoc (char * line)"

.PP
Definition at line \fB15\fP of file \fBheredoc\&.c\fP\&.
.nf
16 {
17     char    **parsed;
18 
19     parsed = ft_split(line, ' ');
20     if (!ft_strcmp(parsed[0], "cat") && !ft_strcmp(parsed[1], "<<"))
21         return (heredoc("EOF"));
22     else
23         return (line);
24 }
.PP
.fi

.PP
References \fBft_split()\fP, \fBft_strcmp()\fP, and \fBheredoc()\fP\&.
.SS "char * heredoc (char * eof)"

.PP
Definition at line \fB26\fP of file \fBheredoc\&.c\fP\&.
.nf
27 {
28     char    *line;
29     char    *comb;
30 
31     comb = "";
32     while (1)
33     {
34         line = readline("heredoc>");
35         if (!ft_strcmp(line, eof))
36             return (comb);
37         comb = ft_strjoin(ft_strjoin(comb, line), "\\n");
38         free(line);
39     }
40 }
.PP
.fi

.PP
References \fBft_strcmp()\fP, and \fBft_strjoin()\fP\&.
.PP
Referenced by \fBcheck_heredoc()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
