.TH "/Users/dimadem/Documents/GitHub/minishell/src/utils/initialise.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/utils/initialise.c
.SH SYNOPSIS
.br
.PP
\fR#include 'tokens\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_ms_data\fP (\fBt_ms_data\fP *data, char **envp)"
.br
.ti -1c
.RI "void \fBinitialise\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_ms_data (\fBt_ms_data\fP * data, char ** envp)"

.PP
Definition at line \fB16\fP of file \fBinitialise\&.c\fP\&.
.nf
17 {
18     data\->args = NULL;
19     data\->envp = NULL;
20     init_env(&data\->envp, envp);
21     data\->local_env = NULL;
22     data\->current_dir = getcwd(NULL, 0);
23     data\->exit_status = 0;
24     data\->std_in = \-1;
25     data\->std_out = \-1;
26     data\->std_err = 2;
27 }
.PP
.fi

.PP
References \fBs_ms_data::args\fP, \fBs_ms_data::current_dir\fP, \fBs_ms_data::envp\fP, \fBs_ms_data::exit_status\fP, \fBinit_env()\fP, \fBs_ms_data::local_env\fP, \fBs_ms_data::std_err\fP, \fBs_ms_data::std_in\fP, and \fBs_ms_data::std_out\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void initialise (int argc, char ** argv)"

.PP
Definition at line \fB29\fP of file \fBinitialise\&.c\fP\&.
.nf
30 {
31     if (argc > 1)
32     {
33         printf("Usage: %s\\n", argv[0]);
34         exit(EXIT_FAILURE);
35     }
36     read_history(HISTORY_PATH);
37 }
.PP
.fi

.PP
References \fBHISTORY_PATH\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
