.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/isnum_from_str.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/isnum_from_str.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisnum_from_str\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isnum_from_str (const char * str)"

.PP
Definition at line \fB15\fP of file \fBisnum_from_str\&.c\fP\&.
.nf
16 {
17     if (!str || *str == '\\0')
18         return (0);
19     if (*str == '\-' || *str == '+')
20     {
21         str++;
22         if (*str == '\\0')
23             return (0);
24     }
25     while (*str)
26     {
27         if (*str < '0' || *str > '9')
28             return (0);
29         str++;
30     }
31     return (1);
32 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
