.TH "/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/list_len_str.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/lib/libft/src/list_len_str.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlist_len_str\fP (char *a[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int list_len_str (char * a[])"

.PP
Definition at line \fB15\fP of file \fBlist_len_str\&.c\fP\&.
.nf
16 {
17     int i;
18 
19     i = 0;
20     while (a[i])
21         i++;
22     return (i);
23 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
