.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_in.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_in.c
.SH SYNOPSIS
.br
.PP
\fR#include 'tokens\&.h'\fP
.br
\fR#include 'shell\&.h'\fP
.br
\fR#include 'redirection\&.h'\fP
.br
\fR#include 'execute\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/wait\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBredirect_in\fP (\fBt_ast\fP *node, \fBt_ms_data\fP *data)"
.br
.RI "redirection input in context of executing AST "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int redirect_in (\fBt_ast\fP * node, \fBt_ms_data\fP * data)"

.PP
redirection input in context of executing AST --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fInode\fP current node in the AST
.RE
.PP

.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIdata\fP minishell structure data
.RE
.PP

.IP "\(bu" 2
\fBReturns\fP
.RS 4
status:
.RE
.PP

.IP "\(bu" 2
0: success
.IP "\(bu" 2
1: error 
.PP

.PP
Definition at line \fB38\fP of file \fBredirect_in\&.c\fP\&.
.nf
39 {
40     pid_t   pid;
41 
42     pid = fork();
43     if (pid == \-1)
44         return (1);
45     if (pid == 0)
46     {
47         data\->std_in = open_file(node\->right, "<");
48         if (data\->std_in == \-1)
49             return (1);
50         execute_ast(node\->left, data);
51         exit(0);
52     }
53     waitpid(pid, &data\->exit_status, 0);
54     return (0);
55 }
.PP
.fi

.PP
References \fBexecute_ast()\fP, \fBs_ms_data::exit_status\fP, \fBs_ast::left\fP, \fBopen_file()\fP, \fBs_ast::right\fP, and \fBs_ms_data::std_in\fP\&.
.PP
Referenced by \fBexecute_ast()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
