.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_append.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_append.c
.SH SYNOPSIS
.br
.PP
\fR#include 'shell\&.h'\fP
.br
\fR#include 'tokens\&.h'\fP
.br
\fR#include 'redirection\&.h'\fP
.br
\fR#include 'execute\&.h'\fP
.br
\fR#include <sys/wait\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBredirect_append\fP (\fBt_ast\fP *node, \fBt_ms_data\fP *data)"
.br
.RI "redirect append '>>' to the end of the file output "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int redirect_append (\fBt_ast\fP * node, \fBt_ms_data\fP * data)"

.PP
redirect append '>>' to the end of the file output --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fInode\fP current node in the AST
.RE
.PP

.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIdata\fP minishell data structure
.RE
.PP

.IP "\(bu" 2
\fBReturns\fP
.RS 4
status:
.RE
.PP

.IP "\(bu" 2
0: success
.IP "\(bu" 2
1: error 
.PP

.PP
Definition at line \fB31\fP of file \fBredirect_append\&.c\fP\&.
.nf
32 {
33     pid_t   pid;
34     int     status;
35 
36     pid = fork();
37     if (pid == \-1)
38         return (1);
39     if (pid == 0)
40     {
41         data\->std_out = open_file(node\->right, ">>");
42         if (data\->std_out == \-1)
43             return (1);
44         execute_ast(node\->left, data);
45         exit(0);
46     }
47     waitpid(pid, &status, 0);
48     return (WEXITSTATUS(status));
49 }
.PP
.fi

.PP
References \fBexecute_ast()\fP, \fBs_ast::left\fP, \fBopen_file()\fP, \fBs_ast::right\fP, and \fBs_ms_data::std_out\fP\&.
.PP
Referenced by \fBexecute_ast()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
