.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_out.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_out.c
.SH SYNOPSIS
.br
.PP
\fR#include 'tokens\&.h'\fP
.br
\fR#include 'shell\&.h'\fP
.br
\fR#include 'redirection\&.h'\fP
.br
\fR#include 'execute\&.h'\fP
.br
\fR#include 'pipe\&.h'\fP
.br
\fR#include <sys/wait\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBredirect_out\fP (\fBt_ast\fP *node, \fBt_ms_data\fP *data)"
.br
.RI "redirect out '>' to the file output "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int redirect_out (\fBt_ast\fP * node, \fBt_ms_data\fP * data)"

.PP
redirect out '>' to the file output --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fInode\fP current node in the AST
.RE
.PP

.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIdata\fP minishell data structure
.RE
.PP

.IP "\(bu" 2
\fBReturns\fP
.RS 4
status:
.RE
.PP

.IP "\(bu" 2
0: success
.IP "\(bu" 2
1: error 
.PP

.PP
Definition at line \fB32\fP of file \fBredirect_out\&.c\fP\&.
.nf
33 {
34     pid_t   pid;
35     int     status;
36 
37     pid = fork();
38     if (pid == \-1)
39         return (1);
40     if (pid == 0)
41     {
42         data\->std_out = open_file(node\->right, ">");
43         if (data\->std_out == \-1)
44             return (1);
45         execute_ast(node\->left, data);
46         exit(0);
47     }
48     waitpid(pid, &status, 0);
49     return (WEXITSTATUS(status));
50 }
.PP
.fi

.PP
References \fBexecute_ast()\fP, \fBs_ast::left\fP, \fBopen_file()\fP, \fBs_ast::right\fP, and \fBs_ms_data::std_out\fP\&.
.PP
Referenced by \fBexecute_ast()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
