.TH "s_ast" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_ast
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tokens\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_token_type\fP \fBtype\fP"
.br
.ti -1c
.RI "char ** \fBargs\fP"
.br
.ti -1c
.RI "struct \fBs_ast\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBs_ast\fP * \fBright\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBtokens\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char** s_ast::args"

.PP
Definition at line \fB51\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBcreate_redir_node()\fP, \fBexecute_ast()\fP, \fBfree_ast()\fP, \fBmanage_commands()\fP, \fBnew_ast_node()\fP, \fBopen_file()\fP, \fBprint_ast_node()\fP, and \fBset_command_args()\fP\&.
.SS "struct \fBs_ast\fP* s_ast::left"

.PP
Definition at line \fB52\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBbuiltin_pipe()\fP, \fBclr_node()\fP, \fBcreate_redir()\fP, \fBcreate_redir_node()\fP, \fBfree_ast()\fP, \fBmanage_pipe()\fP, \fBnew_ast_node()\fP, \fBprint_ast_graphical()\fP, \fBredirect_in()\fP, and \fBredirect_out()\fP\&.
.SS "struct \fBs_ast\fP* s_ast::right"

.PP
Definition at line \fB53\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBbuiltin_pipe()\fP, \fBclr_node()\fP, \fBcreate_redir()\fP, \fBcreate_redir_node()\fP, \fBfree_ast()\fP, \fBmanage_pipe()\fP, \fBnew_ast_node()\fP, \fBprint_ast_graphical()\fP, \fBredirect_in()\fP, and \fBredirect_out()\fP\&.
.SS "\fBt_token_type\fP s_ast::type"

.PP
Definition at line \fB50\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBcreate_redir_node()\fP, \fBexecute_ast()\fP, \fBfree_ast()\fP, \fBnew_ast_node()\fP, and \fBprint_ast_node()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
