.TH "s_env" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_env
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBs_env\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBenv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char* s_env::key"

.PP
Definition at line \fB18\fP of file \fBenv\&.h\fP\&.
.PP
Referenced by \fBadd_env_node()\fP, \fBenv_to_array()\fP, \fBfree_env()\fP, \fBfree_env_list()\fP, \fBget_env()\fP, \fBprint_env_stack()\fP, \fBset_env()\fP, and \fBunset_env()\fP\&.
.SS "struct \fBs_env\fP* s_env::next"

.PP
Definition at line \fB20\fP of file \fBenv\&.h\fP\&.
.PP
Referenced by \fBadd_env_node()\fP, \fBbuiltin_export()\fP, \fBenv_to_array()\fP, \fBfree_env()\fP, \fBfree_env_list()\fP, \fBget_env()\fP, \fBprint_env_stack()\fP, \fBset_env()\fP, and \fBunset_env()\fP\&.
.SS "char* s_env::value"

.PP
Definition at line \fB19\fP of file \fBenv\&.h\fP\&.
.PP
Referenced by \fBadd_env_node()\fP, \fBenv_to_array()\fP, \fBfree_env()\fP, \fBfree_env_list()\fP, \fBget_env()\fP, \fBprint_env_stack()\fP, \fBset_env()\fP, and \fBunset_env()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
