.TH "s_loop_data" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_loop_data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tokens\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBprompt\fP"
.br
.ti -1c
.RI "char * \fBinput\fP"
.br
.ti -1c
.RI "char * \fBtrimmed_input\fP"
.br
.ti -1c
.RI "\fBt_token\fP * \fBtokens\fP"
.br
.ti -1c
.RI "\fBt_ast\fP * \fBtree\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBtokens\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char* s_loop_data::input"

.PP
Definition at line \fB59\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBmain_loop()\fP\&.
.SS "char* s_loop_data::prompt"

.PP
Definition at line \fB58\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBmain_loop()\fP, and \fBstatus_handler()\fP\&.
.SS "\fBt_token\fP* s_loop_data::tokens"

.PP
Definition at line \fB61\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBmain_loop()\fP, and \fBstatus_handler()\fP\&.
.SS "\fBt_ast\fP* s_loop_data::tree"

.PP
Definition at line \fB62\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBmain_loop()\fP, and \fBstatus_handler()\fP\&.
.SS "char* s_loop_data::trimmed_input"

.PP
Definition at line \fB60\fP of file \fBtokens\&.h\fP\&.
.PP
Referenced by \fBmain_loop()\fP, and \fBstatus_handler()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
