.TH "/Users/dimadem/Documents/GitHub/minishell/inc/shell.h" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/inc/shell.h
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBs_ms_data\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_ms_data\fP \fBt_ms_data\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_ms_data\fP \fBt_ms_data\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
