.TH "/Users/dimadem/Documents/GitHub/minishell/src/test/test.h" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/test/test.h
.SH SYNOPSIS
.br
.PP
\fR#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBenv_tests\fP (\fBt_ms_data\fP *data, char **envp)"
.br
.ti -1c
.RI "void \fBpipe_tests\fP (\fBt_ms_data\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void env_tests (\fBt_ms_data\fP * data, char ** envp)"

.PP
Definition at line \fB25\fP of file \fBenv_test\&.c\fP\&.
.nf
26 {
27     printf("\\nENV TESTS\\n");
28     test_init_env(data, envp);
29     test_get_env(data, envp);
30     test_set_env(data, envp);
31     test_unset_env(data);
32     free_env(data\->envp);
33 }
.PP
.fi

.PP
References \fBs_ms_data::envp\fP, \fBfree_env()\fP, \fBtest_get_env()\fP, \fBtest_init_env()\fP, \fBtest_set_env()\fP, and \fBtest_unset_env()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void pipe_tests (\fBt_ms_data\fP * data)"

.PP
Definition at line \fB22\fP of file \fBpipe_test\&.c\fP\&.
.nf
23 {
24     printf("\\nPIPE TESTS\\n");
25     builtin_pipe_test(data);
26     printf("\\033[0m");
27     printf("\\033[0;32m");
28     printf("pipe_test    \-> OK\\n");
29     printf("\\033[0m");
30 }
.PP
.fi

.PP
References \fBbuiltin_pipe_test()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
