.TH "/Users/dimadem/Documents/GitHub/minishell/src/builtins/unset.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/builtins/unset.c
.SH SYNOPSIS
.br
.PP
\fR#include 'shell\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbuiltin_unset\fP (\fBt_ms_data\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int builtin_unset (\fBt_ms_data\fP * data)"

.PP
Definition at line \fB26\fP of file \fBunset\&.c\fP\&.
.nf
27 {
28     int i;
29     int ret;
30 
31     i = 0;
32     ret = 0;
33     while (data\->args[++i])
34     {
35         if (unset_env(&data\->envp, data\->args[i]) == \-1)
36         {
37             ft_putstr_fd("bash: unset: `", STDERR_FILENO);
38             ft_putstr_fd(data\->args[i], STDERR_FILENO);
39             ft_putendl_fd("': not a valid identifier", STDERR_FILENO);
40             ret = 1;
41         }
42     }
43     data\->exit_status = ret;
44     return (ret);
45 }
.PP
.fi

.PP
References \fBs_ms_data::args\fP, \fBs_ms_data::envp\fP, \fBs_ms_data::exit_status\fP, \fBft_putendl_fd()\fP, \fBft_putstr_fd()\fP, and \fBunset_env()\fP\&.
.PP
Referenced by \fBexecute()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
