.TH "/Users/dimadem/Documents/GitHub/minishell/src/redirection/utils.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/redirection/utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'shell\&.h'\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'tokens\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopen_file\fP (\fBt_ast\fP *node, char *direction)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int open_file (\fBt_ast\fP * node, char * direction)"

.PP
Definition at line \fB10\fP of file \fButils\&.c\fP\&.
.nf
11 {
12     int fd;
13     
14     if (ft_strcmp(direction, ">") == 0)
15         fd = open(node\->args[0], O_WRONLY | O_CREAT | O_TRUNC, 0644);
16     else if (ft_strcmp(direction, ">>") == 0)
17         fd = open(node\->args[0], O_WRONLY | O_CREAT | O_APPEND, 0644);
18     else if (ft_strcmp(direction, "<") == 0)
19         fd = open(node\->args[0], O_RDONLY);
20     else if (ft_strcmp(direction, "tty") == 0)
21         fd = open("/dev/tty", O_RDWR);
22     else
23         fd = \-1;
24     return (fd);
25 }
.PP
.fi

.PP
References \fBs_ast::args\fP, and \fBft_strcmp()\fP\&.
.PP
Referenced by \fBexecute_redirect()\fP, and \fBredirect_in()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
