.TH "/Users/dimadem/Documents/GitHub/minishell/src/execute/utils_0.c" 3 "Version 1" "maxishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/dimadem/Documents/GitHub/minishell/src/execute/utils_0.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_free_2d_arr\fP (char **arr)"
.br
.RI "clean up 2d array "
.ti -1c
.RI "int \fBft_perror\fP (char *str)"
.br
.RI "return error message and exit "
.ti -1c
.RI "void \fBclose_fds\fP (int in, int out)"
.br
.RI "close two file descriptors "
.ti -1c
.RI "void \fBhandle_temp_fd\fP (\fBt_ms_data\fP *data)"
.br
.ti -1c
.RI "void \fBhandle_io_fd\fP (\fBt_ms_data\fP *data)"
.br
.RI "close temporary input/output file descriptors and reset them to -1 "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void close_fds (int in, int out)"

.PP
close two file descriptors --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIfds\fP file descriptors 
.RE
.PP

.PP

.PP
Definition at line \fB58\fP of file \fButils_0\&.c\fP\&.
.nf
59 {
60     close(in);
61     close(out);
62 }
.PP
.fi

.PP
Referenced by \fBbuiltin_pipe()\fP, \fBexecute_child()\fP, and \fBnew_process()\fP\&.
.SS "void ft_free_2d_arr (char ** arr)"

.PP
clean up 2d array --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIarr\fP simple two dimensional array 
.RE
.PP

.PP

.PP
Definition at line \fB28\fP of file \fButils_0\&.c\fP\&.
.nf
29 {
30     int i;
31 
32     i = \-1;
33     while (arr[++i] != NULL)
34         free(arr[i]);
35     free(arr);
36 }
.PP
.fi

.PP
Referenced by \fBft_find_path()\fP\&.
.SS "int ft_perror (char * str)"

.PP
return error message and exit --
.IP "\(bu" 2
\fBParameters\fP
.RS 4
\fIstr\fP paste the error message
.RE
.PP

.IP "\(bu" 2
\fBReturns\fP
.RS 4
int return status:
.RE
.PP

.IP "\(bu" 2
- 1: EXIT_FAILURE 
.PP

.PP
Definition at line \fB46\fP of file \fButils_0\&.c\fP\&.
.nf
47 {
48     perror (str);
49     exit(EXIT_FAILURE);
50 }
.PP
.fi

.PP
Referenced by \fBbuiltin_pipe()\fP, \fBexecute()\fP, \fBexecute_child()\fP, \fBexecute_child()\fP, \fBnew_process()\fP, and \fBopen_tmp_file()\fP\&.
.SS "void handle_io_fd (\fBt_ms_data\fP * data)"

.PP
close temporary input/output file descriptors and reset them to -1 -- 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP minishell structure 
.RE
.PP

.PP
Definition at line \fB69\fP of file \fButils_0\&.c\fP\&.
.nf
70 {
71     if (data\->std_in != \-1 && data\->std_out != \-1)
72     {
73         close(data\->std_in);
74         close(data\->std_out);
75         data\->std_in = \-1;
76         data\->std_out = \-1;
77     }
78 }
.PP
.fi

.PP
References \fBs_ms_data::std_in\fP, and \fBs_ms_data::std_out\fP\&.
.PP
Referenced by \fBmain_loop()\fP\&.
.SS "void handle_temp_fd (\fBt_ms_data\fP * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for maxishell from the source code\&.
