maxishell: /Users/dimadem/Documents/GitHub/minishell/inc/builtins.h File Reference
builtins.h File Reference
#include "shell.h"
Functions
int builtin_cd (t_ms_data *data)
int builtin_echo (t_ms_data *data)
int builtin_env (t_ms_data *data)
int builtin_exit (t_ms_data *data)
int builtin_export (t_ms_data *data)
int builtin_pwd (t_ms_data *data)
int builtin_unset (t_ms_data *data)
Function Documentation
builtin_cd()
int builtin_cd (t_ms_data * data)
Definition at line 26 of file cd.c.
{
    char    *target_dir;
    char    *home_dir;
    char    cwd[4096];
    printf("builtin_cd\n");
    home_dir = get_env(data->envp, "HOME");
    target_dir = (char *)data->args[1];
    if (!target_dir)
        target_dir = home_dir;
    if (chdir(target_dir) != 0)
    {
        ft_putstr_fd("bash: cd: ", 2);
        perror(target_dir);
        return (1);
    }
    set_env(&data->envp, "OLDPWD", get_env(data->envp, "PWD"));
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        set_env(&data->envp, "PWD", cwd);
    return (0);
}
References s_ms_data::args, s_ms_data::envp, ft_putstr_fd(), get_env(), and set_env().
Referenced by execute().
builtin_echo()
int builtin_echo (t_ms_data * data)
Definition at line 21 of file echo.c.
{
    int newline;
    int i;
    newline = 1;
    if (data->args[1] && (ft_strcmp(data->args[1], "-n") == 0))
    {
        newline = 0;
        data->args++;
    }
    i = 0;
    while (data->args[++i])
    {
        write(1, data->args[i], ft_strlen(data->args[i]));
        if (data->args[i + 1])
            write(1, " ", 1);
    }
    if (newline)
        write(1, "\n", 1);
    return (0);
}
References s_ms_data::args, ft_strcmp(), and ft_strlen().
Referenced by execute().
builtin_env()
int builtin_env (t_ms_data * data)
Definition at line 38 of file env.c.
{
    printf("\nbuiltin_env\n");
    if (ft_strcmp(data->args[0], "env") == 0 && data->args[1] == NULL)
        print_env_stack(data->envp);
    return (0);
}
References s_ms_data::args, s_ms_data::envp, ft_strcmp(), and print_env_stack().
Referenced by execute().
builtin_exit()
int builtin_exit (t_ms_data * data)
Definition at line 26 of file exit.c.
{
    const char  *message;
    printf("\nbuiltin_exit\n");
    message = "exit\n";
    write(STDOUT_FILENO, message, ft_strlen(message));
    exit(data->exit_status);
}
References s_ms_data::exit_status, and ft_strlen().
Referenced by execute().
builtin_export()
int builtin_export (t_ms_data * data)
Definition at line 28 of file export.c.
{
    t_env   *curr_node;
    char    *key;
    key = NULL;
    if ((data->args[1] == NULL && data->args[2] == NULL) \
            || ft_strncmp(data->args[1], "-p", 2) == 0)
    {
        curr_node = data->envp;
        while (curr_node)
            curr_node = curr_node->next;
    }
    else
        add_env(key, data);
    return (0);
}
References add_env(), s_ms_data::args, s_ms_data::envp, ft_strncmp(), and s_env::next.
Referenced by execute().
builtin_pwd()
int builtin_pwd (t_ms_data * data)
Definition at line 23 of file pwd.c.
{
    char    cwd[4096];
    (void)data;
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        ft_putendl_fd(cwd, STDOUT_FILENO);
    else
    {
        ft_putstr_fd("bash: cd: ", 2);
        perror("cwd");
        return (1);
    }
    return (0);
}
References ft_putendl_fd(), and ft_putstr_fd().
Referenced by execute().
builtin_unset()
int builtin_unset (t_ms_data * data)
Definition at line 26 of file unset.c.
{
    int i;
    int ret;
    i = 0;
    ret = 0;
    while (data->args[++i])
    {
        if (unset_env(&data->envp, data->args[i]) == -1)
        {
            ft_putstr_fd("bash: unset: `", STDERR_FILENO);
            ft_putstr_fd(data->args[i], STDERR_FILENO);
            ft_putendl_fd("': not a valid identifier", STDERR_FILENO);
            ret = 1;
        }
    }
    data->exit_status = ret;
    return (ret);
}
References s_ms_data::args, s_ms_data::envp, s_ms_data::exit_status, ft_putendl_fd(), ft_putstr_fd(), and unset_env().
Referenced by execute().