maxishell: /Users/dimadem/Documents/GitHub/minishell/src/builtins/cd.c File Reference
cd.c File Reference
#include <stdio.h>
#include "libft.h"
#include "shell.h"
#include "env.h"
Functions
int builtin_cd (t_minishell_data *data)
Function Documentation
builtin_cd()
int builtin_cd (t_minishell_data * data)
Definition at line 26 of file cd.c.
{
    char    *target_dir;
    char    *home_dir;
    char    cwd[4096];
    printf("builtin_cd\n");
    home_dir = get_env(data->envp, "HOME");
    target_dir = (char *)data->args[1];
    if (!target_dir)
        target_dir = home_dir;
    if (chdir(target_dir) != 0)
    {
        ft_putstr_fd("bash: cd: ", 2);
        perror(target_dir);
        return (1);
    }
    set_env(&data->envp, "OLDPWD", get_env(data->envp, "PWD"));
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        set_env(&data->envp, "PWD", cwd);
    return (0);
}
References s_minishell_data::args, s_minishell_data::envp, ft_putstr_fd(), get_env(), and set_env().
Referenced by execute().