maxishell: /Users/dimadem/Documents/GitHub/minishell/src/utils/clean_tree.c File Reference
clean_tree.c File Reference
#include "tokens.h"
Functions
void free_all_tokens (t_token *tokens)
void free_ast (t_ast *node)
Function Documentation
free_all_tokens()
void free_all_tokens (t_token * tokens)
Definition at line 16 of file clean_tree.c.
{
    t_token *temp;
    while (tokens)
    {
        temp = tokens;
        tokens = tokens->next;
        if (temp)
        {
            if (temp->data)
            {
                free(temp->data);
                temp->data = NULL;
            }
        }
        free(temp);
        temp = NULL;
    }
}
References s_token::data, and s_token::next.
free_ast()
void free_ast (t_ast * node)
Definition at line 37 of file clean_tree.c.
{
    int             i;
    i = 0;
    if (!node)
        return ;
    if (node->type == PHRASE && node->args)
    {
        while (node->args && node->args[i])
        {
            free(node->args[i]);
            i++;
        }
        free(node->args);
    }
    free_ast(node->left);
    free_ast(node->right);
    free(node);
}
References s_ast::args, free_ast(), s_ast::left, PHRASE, s_ast::right, and s_ast::type.
Referenced by free_ast(), and loop_cleanup().