maxishell: /Users/dimadem/Documents/GitHub/minishell/src/utils/clean_general.c File Reference
clean_general.c File Reference
#include "tokens.h"
#include "env.h"
Functions
void free_args (char **args)
void free_env_list (t_env *env)
void free_ms_data (t_ms_data *data)
void loop_cleanup (char *line, t_token *tokens, char *prompt, t_ast *tree)
Function Documentation
free_args()
void free_args (char ** args)
Definition at line 16 of file clean_general.c.
{
    int i;
    i = 0;
    if (args)
    {
        while (args[i] != NULL)
            free(args[i++]);
        free(args);
    }
}
Referenced by free_ms_data().
free_env_list()
void free_env_list (t_env * env)
Definition at line 29 of file clean_general.c.
{
    t_env   *temp;
    while (env)
    {
        free(env->key);
        free(env->value);
        temp = env;
        env = env->next;
        free(temp);
    }
}
References s_env::key, s_env::next, and s_env::value.
Referenced by free_ms_data().
free_ms_data()
void free_ms_data (t_ms_data * data)
Definition at line 43 of file clean_general.c.
{
    if (data)
    {
        free_args(data->args);
        free_env_list(data->envp);
        free_env_list(data->local_env);
        free(data->current_dir);
        free(data);
    }
}
References s_ms_data::args, s_ms_data::current_dir, s_ms_data::envp, free_args(), free_env_list(), and s_ms_data::local_env.
Referenced by main().
loop_cleanup()
void loop_cleanup (char * line, t_token * tokens, char * prompt, t_ast * tree)
Definition at line 55 of file clean_general.c.
{
    free(line);
    free(prompt);
    (void)tokens;
    free_ast(tree);
}
References free_ast().
Referenced by main_loop(), and status_handler().