maxishell: /Users/dimadem/Documents/GitHub/minishell/src/builtins/echo.c File Reference
echo.c File Reference
#include "libft.h"
#include "shell.h"
Functions
int builtin_echo (t_minishell_data *data)
Function Documentation
builtin_echo()
int builtin_echo (t_minishell_data * data)
Definition at line 21 of file echo.c.
{
    int newline;
    int i;
    newline = 1;
    if (ft_strcmp(data->args[1], "-n") == 0)
    {
        newline = 0;
        data->args++;
    }
    i = 0;
    while (data->args[++i])
    {
        write(1, data->args[i], ft_strlen(data->args[i]));
        if (data->args[i + 1])
            write(1, " ", 1);
    }
    if (newline)
        write(1, "\n", 1);
    return (0);
}
References s_minishell_data::args, ft_strcmp(), and ft_strlen().
Referenced by execute().