maxishell: /Users/dimadem/Documents/GitHub/minishell/src/execute/execute.c File Reference
execute.c File Reference
#include "builtins.h"
#include "libft.h"
#include <stdio.h>
#include <sys/wait.h>
#include "shell.h"
#include "execute.h"
#include "tokens.h"
#include "pipe.h"
#include "redirection.h"
Functions
int execute_ast (t_ast *node, t_minishell_data *data)
execute Abstract Syntax Tree
int execute (t_minishell_data *data)
execute distribution function checks if the command is a builtin or a new process
int new_process (t_minishell_data *data)
executes a new process
Function Documentation
execute()
int execute (t_minishell_data * data)
execute distribution function checks if the command is a builtin or a new process
--
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 93 of file execute.c.
{
    size_t  i;
    char    *builtin_commands[7];
    int     (*builtin_functions[7])(t_minishell_data *);
    builtin_commands[0] = "cd";
    builtin_commands[1] = "echo";
    builtin_commands[2] = "env";
    builtin_commands[3] = "exit";
    builtin_commands[4] = "export";
    builtin_commands[5] = "pwd";
    builtin_commands[6] = "unset";
    builtin_functions[0] = &builtin_cd;
    builtin_functions[1] = &builtin_echo;
    builtin_functions[2] = &builtin_env;
    builtin_functions[3] = &builtin_exit;
    builtin_functions[4] = &builtin_export;
    builtin_functions[5] = &builtin_pwd;
    builtin_functions[6] = &builtin_unset;
    if (data->args[0] == NULL)
        return (2);
    i = -1;
    while (++i < sizeof(builtin_commands) / sizeof(char *))
        if (ft_strcmp(data->args[0], builtin_commands[i]) == 0)
            return ((*builtin_functions[i])(data));
    return (new_process(data));
}
References s_minishell_data::args, builtin_cd(), builtin_echo(), builtin_env(), builtin_exit(), builtin_export(), builtin_pwd(), builtin_unset(), ft_strcmp(), and new_process().
Referenced by execute_ast().
execute_ast()
int execute_ast (t_ast * node, t_minishell_data * data)
execute Abstract Syntax Tree
--
Parameters
node Abstract Syntax Tree Node
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 41 of file execute.c.
{
    if (!node)
        return (1);
    if (node->type == PIPE)
    {
        printf(RED"PIPE\n"RESET);
        return (builtin_pipe(node, data));
    }
    else if (node->type == ENV_VAR)     // "$()"
    {
        printf(BLU"ENV_VAR\n"RESET);
        //execute_redirect(node, data);
    }
    else if (node->type == REDIR_IN)
    {
        printf(GRN"REDIR_IN\n"RESET);
        return (redirect_in(node, data));
    }
    else if (node->type == REDIR_OUT)   // ">"
    {
        printf(CYA"REDIR_OUT\n"RESET);
        return (redirect_out(node, data));
    }
    else if (node->type == REDIR_APPEND) // ">>"
    {
        printf(CYA"REDIR_APPEND\n"RESET);
        return (redirect_append(node, data));
    }
    else if (node->type == REDIR_HEREDOC) // "<<"
    {
        printf(MAG"REDIR_HEREDOC\n"RESET);
        return (redirect_here_doc(node, data));
    }
    else if (node->type == PHRASE)
    {
        printf(YEL"PHRASE\n"RESET);
        data->args = node->args;
        return (execute(data));
    }
    return (0);
}
References s_ast::args, s_minishell_data::args, BLU, builtin_pipe(), CYA, ENV_VAR, execute(), GRN, MAG, PHRASE, PIPE, RED, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, REDIR_OUT, redirect_append(), redirect_here_doc(), redirect_in(), redirect_out(), RESET, s_ast::type, and YEL.
Referenced by execute_child(), main_loop(), redirect_append(), redirect_here_doc(), redirect_in(), and redirect_out().
new_process()
int new_process (t_minishell_data * data)
executes a new process
--
Parameters
data minishell data structure
Returns
int return status:
- 0: success
- 1: error
Definition at line 131 of file execute.c.
{
    pid_t   pid;
    printf("new_process\n");
    printf("data->std_in: %d\n", data->std_in);
    printf("data->std_out: %d\n", data->std_out);
    if(data->std_in == -1)
        data->std_in = dup(STDIN_FILENO);
    if(data->std_out == -1)
        data->std_out = dup(STDOUT_FILENO);
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        if (data->std_in != -1)
            dup2(data->std_in, STDIN_FILENO);
        if (data->std_out != -1)
            dup2(data->std_out, STDOUT_FILENO);
        close_fds(data->std_in, data->std_out);
        if (execve(ft_find_path(data->args[0], data->envp), \
                data->args, env_to_array(data->envp)) == -1)
            ft_perror("minishell");
    }
    waitpid(pid, &data->exit_status, 0);
    close_fds(data->std_in, data->std_out);
    return (0);
}
References s_minishell_data::args, close_fds(), env_to_array(), s_minishell_data::envp, s_minishell_data::exit_status, ft_find_path(), ft_perror(), s_minishell_data::std_in, and s_minishell_data::std_out.
Referenced by execute().