maxishell: /Users/dimadem/Documents/GitHub/minishell/src/builtins/export.c File Reference
export.c File Reference
#include "env.h"
#include "libft.h"
#include <stdlib.h>
#include "shell.h"
#include <stdio.h>
Functions
int builtin_export (t_minishell_data *data)
void add_env (char *key, t_minishell_data *data)
Function Documentation
add_env()
void add_env (char * key, t_minishell_data * data)
Definition at line 46 of file export.c.
{
    int i;
    i = 0;
    while (data->args[++i])
    {
        if (ft_strchr(data->args[i], '='))
            set_env(&data->envp, data->args[i], \
                    ft_strchr(data->args[i], '=') + 1);
        else
        {
            key = ft_strcdup(data->args[i], '=');
            if (get_env(data->envp, key))
                set_env(&data->envp, key, "");
            else
                set_env(&data->envp, key, NULL);
            free(key);
        }
    }
}
References s_minishell_data::args, s_minishell_data::envp, ft_strcdup(), ft_strchr(), get_env(), and set_env().
Referenced by builtin_export().
builtin_export()
int builtin_export (t_minishell_data * data)
Definition at line 28 of file export.c.
{
    t_env   *curr_node;
    char    *key;
    key = NULL;
    if ((data->args[1] == NULL && data->args[2] == NULL) \
            || ft_strncmp(data->args[1], "-p", 2) == 0)
    {
        curr_node = data->envp;
        while (curr_node)
            curr_node = curr_node->next;
    }
    else
        add_env(key, data);
    return (0);
}
References add_env(), s_minishell_data::args, s_minishell_data::envp, ft_strncmp(), and s_env::next.
Referenced by execute().