maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_print_int.c File Reference
ft_print_int.c File Reference
#include "libft.h"
Functions
int ft_print_int (int n)
Function Documentation
ft_print_int()
int ft_print_int (int n)
Definition at line 15 of file ft_print_int.c.
{
    int     len;
    char    *num;
    num = ft_itoa(n);
    len = ft_print_str(num);
    free(num);
    return (len);
}
References ft_itoa(), and ft_print_str().
Referenced by ft_formatssssss().