maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_memcpy.c File Reference
ft_memcpy.c File Reference
#include "libft.h"
Functions
void * ft_memcpy (void *dest, const void *src, size_t n)
Function Documentation
ft_memcpy()
void * ft_memcpy (void * dest, const void * src, size_t n)
Definition at line 22 of file ft_memcpy.c.
{
    char        *d;
    const char  *s;
    if (!dest && !src)
        return (NULL);
    s = src;
    d = dest;
    while (n--)
        *d++ = *s++;
    return (dest);
}
Referenced by ft_memmove(), ft_strjoin_gnl(), and strndup().