maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_putchar_fd.c File Reference
ft_putchar_fd.c File Reference
#include "libft.h"
Functions
void ft_putchar_fd (char c, int fd)
Function Documentation
ft_putchar_fd()
void ft_putchar_fd (char c, int fd)
Definition at line 20 of file ft_putchar_fd.c.
{
    write(fd, &c, 1);
}
Referenced by ft_print_char(), ft_print_percent(), ft_print_str(), ft_print_unsigned_hex(), ft_put_hex(), ft_put_ptr(), ft_putendl_fd(), and ft_putnbr_fd().