maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strlcpy.c File Reference
ft_strlcpy.c File Reference
#include "libft.h"
Functions
size_t ft_strlcpy (char *dst, const char *src, size_t size)
Function Documentation
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t size)
Definition at line 25 of file ft_strlcpy.c.
{
    char        *d;
    const char  *s;
    size_t      n;
    d = dst;
    s = src;
    n = size;
    if (n > 0)
    {
        while (--n > 0 && *s != '\0')
            *d++ = *s++;
        *d = '\0';
    }
    while (*s != '\0')
        s++;
    return (s - src);
}
Referenced by ft_strdup(), ft_strjoin_gnl(), and ft_strndup().