maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strtrim.c File Reference
ft_strtrim.c File Reference
#include "libft.h"
Functions
static int ft_char_in_set (char c, char const *set)
char * ft_strtrim (char const *s1, char const *set)
Function Documentation
ft_char_in_set()
static int ft_char_in_set (char c, char const * set) static
Definition at line 25 of file ft_strtrim.c.
{
    size_t  i;
    i = 0;
    while (set[i])
    {
        if (set[i] == c)
            return (1);
        i++;
    }
    return (0);
}
Referenced by ft_strtrim().
ft_strtrim()
char * ft_strtrim (char const * s1, char const * set)
Definition at line 39 of file ft_strtrim.c.
{
    char    *str;
    size_t  i;
    size_t  start;
    size_t  end;
    if (!s1 || !set)
        return (NULL);
    start = 0;
    while (s1[start] && ft_char_in_set(s1[start], set))
        start++;
    end = ft_strlen(s1);
    while (end > start && ft_char_in_set(s1[end - 1], set))
        end--;
    str = (char *)malloc(sizeof(*s1) * (end - start + 1));
    if (!str)
        return (NULL);
    i = 0;
    while (start < end)
        str[i++] = s1[start++];
    str[i] = 0;
    return (str);
}
References ft_char_in_set(), and ft_strlen().
Referenced by trim_input().