maxishell: /Users/dimadem/Documents/GitHub/minishell/lib/libft/src/ft_strchr.c File Reference
ft_strchr.c File Reference
#include "libft.h"
Functions
char * ft_strchr (const char *s, int c)
Function Documentation
ft_strchr()
char * ft_strchr (const char * s, int c)
Definition at line 25 of file ft_strchr.c.
{
    unsigned char   uc;
    uc = (unsigned char)c;
    while (*s != '\0' && *s != uc)
        s++;
    if (*s == uc)
        return ((char *)s);
    return (NULL);
}
Referenced by add_env(), add_env_node(), check_operators_loop(), extract_line(), ft_exclude_delimiters(), handle_phrase(), read_from_fd(), and tokenise().