maxishell: /Users/dimadem/Documents/GitHub/minishell/src/parser/input_checker_helpers.c File Reference
input_checker_helpers.c File Reference
#include "tokens.h"
Functions
char * trim_input (char *str)
int valid_operator (const char **str)
Function Documentation
trim_input()
char * trim_input (char * str)
Definition at line 15 of file input_checker_helpers.c.
{
    char    *trimmed_str;
    trimmed_str = ft_strtrim(str, " \t\n\r\v\f");
    if (!trimmed_str)
        return (0);
    return (trimmed_str);
}
References ft_strtrim().
Referenced by main_loop().
valid_operator()
int valid_operator (const char ** str)
Definition at line 25 of file input_checker_helpers.c.
{
    const char  *start;
    start = (*str)++;
    if (*start == **str)
        (*str)++;
    *str = ft_exclude_delimiters(*str, " \t\n\r\v\f");
    if (**str == '<' || **str == '>' || **str == '|' || **str == '\0')
        return (0);
    return (1);
}
References ft_exclude_delimiters().
Referenced by check_redirections().