maxishell: /Users/dimadem/Documents/GitHub/minishell/inc/pipe.h File Reference
pipe.h File Reference
#include "shell.h"
#include "tokens.h"
Macros
#define WAIT_NEXT_COMMAND 1
Functions
int builtin_pipe (t_ast *node, t_ms_data *data)
execute pipe when | is found in the command
Macro Definition Documentation
WAIT_NEXT_COMMAND
#define WAIT_NEXT_COMMAND 1
Definition at line 19 of file pipe.h.
Referenced by builtin_pipe(), and status_handler().
Function Documentation
builtin_pipe()
int builtin_pipe (t_ast * node, t_ms_data * data)
execute pipe when | is found in the command
--
Parameters
node current node in the AST
Parameters
data minishell structure data
Returns
int return status:
- 0: success
- 1: error
Definition at line 35 of file pipe.c.
{
    int     fd[2];
    pid_t   pid_1;
    pid_t   pid_2;
    int     status;
    pid_2 = -1;
    if (pipe(fd) == -1)
        ft_perror("pipe");
    pid_1 = execute_child(node->left, data, fd, 0);
    if (node->right != NULL)
        pid_2 = execute_child(node->right, data, fd, 1);
    else
    {
        close(fd[1]);
        data->std_in = fd[0];
        return (WAIT_NEXT_COMMAND);
    }
    close_fds(fd[0], fd[1]);
    if (pid_1 > 0)
        waitpid(pid_1, &status, 0);
    if (node->right != NULL && pid_2 > 0)
        waitpid(pid_2, &status, 0);
    return (WEXITSTATUS(status));
}
References close_fds(), execute_child(), ft_perror(), s_ast::left, s_ast::right, s_ms_data::std_in, and WAIT_NEXT_COMMAND.
Referenced by builtin_pipe_test(), and execute_ast().