maxishell: /Users/dimadem/Documents/GitHub/minishell/src/test/pipe/pipe_test.c File Reference
pipe_test.c File Reference
#include <assert.h>
#include <stdio.h>
#include "shell.h"
#include "pipe.h"
#include "libft.h"
Functions
void builtin_pipe_test (t_minishell_data *data)
void pipe_tests (t_minishell_data *data)
Function Documentation
builtin_pipe_test()
void builtin_pipe_test (t_minishell_data * data)
Definition at line 32 of file pipe_test.c.
{
    data->args = ft_split("ls -l | wc -l", ' ');
    // builtin_pipe(node, data);
    assert(data->args != NULL);
}
References s_minishell_data::args, and ft_split().
Referenced by pipe_tests().
pipe_tests()
void pipe_tests (t_minishell_data * data)
Definition at line 22 of file pipe_test.c.
{
    printf("\nPIPE TESTS\n");
    builtin_pipe_test(data);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("pipe_test    -> OK\n");
    printf("\033[0m");
}
References builtin_pipe_test().
Referenced by main().