maxishell: /Users/dimadem/Documents/GitHub/minishell/src/pipe/pipe.c File Reference
pipe.c File Reference
#include "shell.h"
#include <unistd.h>
#include "libft.h"
#include "execute.h"
#include <stdio.h>
#include <sys/wait.h>
#include "pipe.h"
Functions
int builtin_pipe (t_ast *node, t_minishell_data *data)
execute pipe when | is found in the command
pid_t execute_child (t_ast *node, t_minishell_data *data, int fd[2], int direction)
execute child process in the pipe context
Function Documentation
builtin_pipe()
int builtin_pipe (t_ast * node, t_minishell_data * data)
execute pipe when | is found in the command
--
Parameters
node current node in the AST
Parameters
data minishell structure data
Returns
int return status:
- 0: success
- 1: error
Definition at line 35 of file pipe.c.
{
    int     fd[2];
    pid_t   pid_1;
    pid_t   pid_2;
    int     status;
    pid_2 = -1;
    if (pipe(fd) == -1)
        ft_perror("pipe");
    pid_1 = execute_child(node->left, data, fd, 0);
    if (node->right != NULL)
        pid_2 = execute_child(node->right, data, fd, 1);
    else
    {
        close(fd[1]);
        data->std_in = fd[0];
        return (WAIT_NEXT_COMMAND);
    }
    close_fds(fd[0], fd[1]);
    if (pid_1 > 0)
        waitpid(pid_1, &status, 0);
    if (node->right != NULL && pid_2 > 0)
        waitpid(pid_2, &status, 0);
    return (WEXITSTATUS(status));
}
References close_fds(), execute_child(), ft_perror(), s_ast::left, s_ast::right, s_minishell_data::std_in, and WAIT_NEXT_COMMAND.
Referenced by execute_ast().
execute_child()
pid_t execute_child (t_ast * node, t_minishell_data * data, int fd[2], int direction)
execute child process in the pipe context
--
Parameters
node current node in the AST
data minishell structure data
fd file descriptors
direction direction of the pipe if 0 - node_left, if 1 - node_right
Returns
pid_t return the process id
Definition at line 71 of file pipe.c.
{
    pid_t   pid;
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        if (direction == 0)
            dup2(fd[1], STDOUT_FILENO);
        else
            dup2(fd[0], STDIN_FILENO);
        close_fds(fd[0], fd[1]);
        execute_ast(node, data);
        exit(EXIT_SUCCESS);
    }
    return (pid);
}
References close_fds(), execute_ast(), and ft_perror().
Referenced by builtin_pipe().