maxishell: /Users/dimadem/Documents/GitHub/minishell/src/builtins/pwd.c File Reference
pwd.c File Reference
#include "shell.h"
#include <unistd.h>
#include "libft.h"
#include <stdio.h>
Functions
int builtin_pwd (t_minishell_data *data)
Function Documentation
builtin_pwd()
int builtin_pwd (t_minishell_data * data)
Definition at line 23 of file pwd.c.
{
    char    cwd[4096];
    (void)data;
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        ft_putendl_fd(cwd, STDOUT_FILENO);
    else
    {
        ft_putstr_fd("bash: cd: ", 2);
        perror("cwd");
        return (1);
    }
    return (0);
}
References ft_putendl_fd(), and ft_putstr_fd().
Referenced by execute().