maxishell: /Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_heredoc.c File Reference
redirect_heredoc.c File Reference
#include "shell.h"
#include "tokens.h"
#include "redirection.h"
#include "execute.h"
#include <fcntl.h>
#include <sys/wait.h>
Functions
int redirect_here_doc (t_ast *node, t_ms_data *data)
This function handle "<<" heredoc functionality.
static int open_tmp_file (const char *type)
static void execute_child (t_ast *node, t_ms_data *data, int *file_fd)
Function Documentation
execute_child()
static void execute_child (t_ast * node, t_ms_data * data, int * file_fd) static
Definition at line 76 of file redirect_heredoc.c.
{
    pid_t   pid;
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        data->std_in = dup(*file_fd);
        execute_ast(node, data);
        exit(0);
    }
    close(*file_fd);
    waitpid(pid, &data->exit_status, 0);
}
References execute_ast(), s_ms_data::exit_status, ft_perror(), and s_ms_data::std_in.
Referenced by redirect_here_doc().
open_tmp_file()
static int open_tmp_file (const char * type) static
Definition at line 62 of file redirect_heredoc.c.
{
    int file_fd;
    file_fd = -1;
    if (ft_strcmp(type, "w") == 0)
        file_fd = open("/tmp/heredoc", O_WRONLY | O_CREAT | O_TRUNC, 0644);
    else if (ft_strcmp(type, "r") == 0)
        file_fd = open("/tmp/heredoc", O_RDONLY);
    if (file_fd < 0)
        ft_perror("open");
    return (file_fd);
}
References ft_perror(), and ft_strcmp().
Referenced by redirect_here_doc().
redirect_here_doc()
int redirect_here_doc (t_ast * node, t_ms_data * data)
This function handle "<<" heredoc functionality.
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status:
0: success
1: error
Definition at line 34 of file redirect_heredoc.c.
{
    char    *line;
    char    *eof;
    int     file_fd;
    line = NULL;
    if (node->right->args[0] == NULL)
        return (1);
    file_fd = open_tmp_file("w");
    eof = ft_strdup(node->right->args[0]);
    line = readline("> ");
    while (line && (ft_strcmp(line, eof) != 0))
    {
        write(file_fd, line, ft_strlen(line));
        write(file_fd, "\n", 1);
        free(line);
        line = readline("> ");
    }
    free(line);
    free(eof);
    close(file_fd);
    file_fd = open_tmp_file("r");
    execute_child(node->left, data, &file_fd);
    unlink("/tmp/heredoc");
    return (0);
}
References s_ast::args, execute_child(), ft_strcmp(), ft_strdup(), ft_strlen(), s_ast::left, open_tmp_file(), and s_ast::right.
Referenced by execute_ast().