maxishell: /Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_append.c File Reference
redirect_append.c File Reference
#include "shell.h"
#include "tokens.h"
#include "redirection.h"
#include "execute.h"
#include <sys/wait.h>
Functions
int redirect_append (t_ast *node, t_ms_data *data)
redirect append ">>" to the end of the file output
Function Documentation
redirect_append()
int redirect_append (t_ast * node, t_ms_data * data)
redirect append ">>" to the end of the file output
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status:
0: success
1: error
Definition at line 31 of file redirect_append.c.
{
    pid_t   pid;
    int     status;
    pid = fork();
    if (pid == -1)
        return (1);
    if (pid == 0)
    {
        data->std_out = open_file(node->right, ">>");
        if (data->std_out == -1)
            return (1);
        execute_ast(node->left, data);
        exit(0);
    }
    waitpid(pid, &status, 0);
    return (WEXITSTATUS(status));
}
References execute_ast(), s_ast::left, open_file(), s_ast::right, and s_ms_data::std_out.
Referenced by execute_ast().