maxishell: /Users/dimadem/Documents/GitHub/minishell/src/redirection/redirect_in.c File Reference
redirect_in.c File Reference
#include "tokens.h"
#include "shell.h"
#include "redirection.h"
#include "execute.h"
#include <string.h>
Functions
int redirect_in (t_ast *node, t_minishell_data *data)
redirection input in context of executing AST
Function Documentation
redirect_in()
int redirect_in (t_ast * node, t_minishell_data * data)
redirection input in context of executing AST
--
Parameters
node current node in the AST
Parameters
data minishell structure data
Returns
status: 0: success 1: error
Definition at line 23 of file redirect_in.c.
{
    pid_t   pid;
    pid = fork();
    if (pid == -1)
        return (1);
    if (pid == 0)
    {
        data->std_in = open_file(node->right, "<");
        if (data->std_in == -1)
            return (1);
        execute_ast(node->left, data);
        exit(0);
    }
    waitpid(pid, &data->exit_status, 0);
    return (0);
}
References execute_ast(), s_minishell_data::exit_status, s_ast::left, open_file(), s_ast::right, and s_minishell_data::std_in.
Referenced by execute_ast().