maxishell: /Users/dimadem/Documents/GitHub/minishell/inc/redirection.h File Reference
redirection.h File Reference
#include "shell.h"
#include "tokens.h"
Functions
int redirect_in (t_ast *node, t_minishell_data *data)
redirection input in context of executing AST
int redirect_out (t_ast *node, t_minishell_data *data)
redirect out ">" to the file output
int redirect_append (t_ast *node, t_minishell_data *data)
redirect append ">>" to the end of the file output
int redirect_here_doc (t_ast *node, t_minishell_data *data)
This function handle "<<" heredoc functionality.
int open_file (t_ast *node, char *direction)
open file in the context of redirection
char * ft_get_next_line (int fd)
Function Documentation
ft_get_next_line()
char * ft_get_next_line (int fd)
Definition at line 41 of file utils.c.
{
    static char *saved = NULL;
    char        *line;
    char        *buf;
    if (fd < 0 || BUFFER_SIZE < 1 || fd > 4095)
        return (NULL);
    buf = malloc(BUFFER_SIZE + 1);
    if (!buf)
        return (NULL);
    saved = read_from_fd(fd, saved, buf);
    if (!saved)
    {
        free(saved);
        saved = NULL;
        return (NULL);
    }
    line = extract_line(&saved);
    if (line == NULL)
    {
        free(saved);
        saved = NULL;
    }
    return (line);
}
References BUFFER_SIZE, extract_line(), and read_from_fd().
open_file()
int open_file (t_ast * node, char * direction)
open file in the context of redirection
-- "<" - read
">" - write
">>" - append
"tty" - open /dev/tty
Parameters
node current node in the AST
Parameters
direction type of redirection
Returns
int file descriptor
Definition at line 24 of file utils.c.
{
    int fd;
    if ((ft_strcmp(direction, "<") == 0) || (ft_strcmp(direction, "read") == 0))
        fd = open(node->args[0], O_RDONLY);
    else if (ft_strcmp(direction, ">") == 0)
        fd = open(node->args[0], O_WRONLY | O_CREAT | O_TRUNC, 0644);
    else if ((ft_strcmp(direction, ">>") == 0) || (ft_strcmp(direction, "temp") == 0))
        fd = open(node->args[0], O_WRONLY | O_CREAT | O_APPEND, 0644);
    else if (ft_strcmp(direction, "tty") == 0)
        fd = open("/dev/tty", O_RDWR);
    else
        fd = -1;
    return (fd);
}
References s_ast::args, and ft_strcmp().
Referenced by redirect_append(), redirect_in(), and redirect_out().
redirect_append()
int redirect_append (t_ast * node, t_minishell_data * data)
redirect append ">>" to the end of the file output
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status: 0: success 1: error
Definition at line 16 of file redirect_append.c.
{
    pid_t pid;
    int status;
    pid = fork();
    if (pid == -1)
        return (1);
    if (pid == 0)
    {
        data->std_out = open_file(node->right, ">>");
        if (data->std_out == -1)
            return (1);
        execute_ast(node->left, data);
        exit(0);
    }
    waitpid(pid, &status, 0);
    return (WEXITSTATUS(status));
}
References execute_ast(), s_ast::left, open_file(), s_ast::right, and s_minishell_data::std_out.
Referenced by execute_ast().
redirect_here_doc()
int redirect_here_doc (t_ast * node, t_minishell_data * data)
This function handle "<<" heredoc functionality.
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status: 0: success 1: error
Definition at line 17 of file redirect_heredoc.c.
{
    char   *line;
    char   *eof;
    int    file_fd;
    pid_t  pid;
    line = NULL;
    if (node->right->args[0] == NULL)
        return (1);
    eof = ft_strdup(node->right->args[0]);
    file_fd = open("/tmp/heredoc", O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (file_fd < 0)
    {
        free(eof);
        return (1);
    }
    line = readline("> ");
    while (line && (ft_strcmp(line, eof) != 0))
    {
        write(data->std_out, line, ft_strlen(line));
        write(data->std_out, "\n", 1);
        free(line);
        line = readline("> ");
    }
    free(line);
    free(eof);
    close(file_fd);
    file_fd = open("/tmp/heredoc", O_RDONLY);
    data->std_in = file_fd;
    if (file_fd < 0)
        return (1);
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        close_fds(data->std_in, data->std_out);
        execute_ast(node->left, data);
        exit(1);
    }
    return (0);
}
References s_ast::args, close_fds(), execute_ast(), ft_perror(), ft_strcmp(), ft_strdup(), ft_strlen(), s_ast::left, s_ast::right, s_minishell_data::std_in, and s_minishell_data::std_out.
Referenced by execute_ast().
redirect_in()
int redirect_in (t_ast * node, t_minishell_data * data)
redirection input in context of executing AST
--
Parameters
node current node in the AST
Parameters
data minishell structure data
Returns
status: 0: success 1: error
Definition at line 23 of file redirect_in.c.
{
    pid_t   pid;
    pid = fork();
    if (pid == -1)
        return (1);
    if (pid == 0)
    {
        data->std_in = open_file(node->right, "<");
        if (data->std_in == -1)
            return (1);
        execute_ast(node->left, data);
        exit(0);
    }
    waitpid(pid, &data->exit_status, 0);
    return (0);
}
References execute_ast(), s_minishell_data::exit_status, s_ast::left, open_file(), s_ast::right, and s_minishell_data::std_in.
Referenced by execute_ast().
redirect_out()
int redirect_out (t_ast * node, t_minishell_data * data)
redirect out ">" to the file output
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status: 0: success 1: error
Definition at line 23 of file redirect_out.c.
{
    pid_t pid;
    int status;
    pid = fork();
    if (pid == -1)
        return (1);
    if (pid == 0)
    {
        data->std_out = open_file(node->right, ">");
        if (data->std_out == -1)
            return (1);
        execute_ast(node->left, data);
        exit(0);
    }
    waitpid(pid, &status, 0);
    return (WEXITSTATUS(status));
}
References execute_ast(), s_ast::left, open_file(), s_ast::right, and s_minishell_data::std_out.
Referenced by execute_ast().