maxishell: /Users/dimadem/Documents/GitHub/minishell/src/test/test.h File Reference
test.h File Reference
#include "shell.h"
Functions
void env_tests (t_minishell_data *data, char **envp)
void pipe_tests (t_minishell_data *data)
Function Documentation
env_tests()
void env_tests (t_minishell_data * data, char ** envp)
Definition at line 25 of file env_test.c.
{
    printf("\nENV TESTS\n");
    test_init_env(data, envp);
    test_get_env(data, envp);
    test_set_env(data, envp);
    test_unset_env(data);
    free_env(data->envp);
}
References s_minishell_data::envp, free_env(), test_get_env(), test_init_env(), test_set_env(), and test_unset_env().
Referenced by main().
pipe_tests()
void pipe_tests (t_minishell_data * data)
Definition at line 22 of file pipe_test.c.
{
    printf("\nPIPE TESTS\n");
    builtin_pipe_test(data);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("pipe_test    -> OK\n");
    printf("\033[0m");
}
References builtin_pipe_test().
Referenced by main().