maxishell: /Users/dimadem/Documents/GitHub/minishell/src/parser/tokeniser.c File Reference
tokeniser.c File Reference
#include "tokens.h"
#include <string.h>
Functions
void handle_special_chars (char **str, t_token **tokens)
void append_phrase_if_valid (char **start, char **str, t_token **tokens)
void handle_phrase (char **str, t_token **tokens)
void print_tokens (t_token *tokens)
t_token * tokenise (char *str)
Function Documentation
append_phrase_if_valid()
void append_phrase_if_valid (char ** start, char ** str, t_token ** tokens)
Definition at line 49 of file tokeniser.c.
{
    char    *phrase;
    if (*str > *start)
    {
        phrase = ft_strndup(*start, *str - *start);
        if (phrase)
        {
            append_token(tokens, new_token(phrase, PHRASE));
            free(phrase);
        }
        else
            ft_printf("Error: unable to allocate memory for token\n");
    }
}
References append_token(), ft_printf(), ft_strndup(), new_token(), and PHRASE.
Referenced by handle_phrase().
handle_phrase()
void handle_phrase (char ** str, t_token ** tokens)
Definition at line 66 of file tokeniser.c.
{
    char    *start;
    char    quote_flag;
    char    quote_type;
    start = *str;
    quote_flag = 0;
    quote_type = 0;
    while (**str)
    {
        if (!quote_flag && (**str == '\'' || **str == '\"'))
        {
            quote_flag = 1;
            quote_type = **str;
        }
        else if (quote_flag && **str == quote_type)
            quote_flag = 0;
        if (!quote_flag && ft_strchr(" \t\n\r\v\f<|>", **str) != NULL)
            break ;
        (*str)++;
    }
    append_phrase_if_valid(&start, str, tokens);
}
References append_phrase_if_valid(), and ft_strchr().
Referenced by tokenise().
handle_special_chars()
void handle_special_chars (char ** str, t_token ** tokens)
Definition at line 22 of file tokeniser.c.
{
    if (**str == '<')
    {
        if (*(*str + 1) == '<')
        {
            append_token(tokens, new_token("<<", REDIR_HEREDOC));
            (*str)++;
        }
        else
            append_token(tokens, new_token("<", REDIR_IN));
    }
    else if (**str == '>')
    {
        if (*(*str + 1) == '>')
        {
            append_token(tokens, new_token(">>", REDIR_APPEND));
            (*str)++;
        }
        else
            append_token(tokens, new_token(">", REDIR_OUT));
    }
    else if (**str == '|')
        append_token(tokens, new_token("|", PIPE));
    (*str)++;
}
References append_token(), new_token(), PIPE, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, and REDIR_OUT.
Referenced by tokenise().
print_tokens()
void print_tokens (t_token * tokens)
Definition at line 91 of file tokeniser.c.
{
    t_token *token;
    int     i;
    i = 0;
    token = tokens;
    while (token != NULL)
    {
        printf("input[%d] ->  %s \n", i, token->data);
        token = token->next;
        i++;
    }
}
References s_token::data, and s_token::next.
tokenise()
t_token * tokenise (char * str)
Definition at line 106 of file tokeniser.c.
{
    t_token *tokens;
    tokens = NULL;
    while (*str)
    {
        while (*str && ft_strchr(" \t\n\r\v\f", *str) != NULL)
            str++;
        if (ft_strchr("<|>", *str) != NULL)
            handle_special_chars(&str, &tokens);
        else
            handle_phrase(&str, &tokens);
    }
    return (tokens);
}
References ft_strchr(), handle_phrase(), and handle_special_chars().
Referenced by main_loop().