maxishell: /Users/dimadem/Documents/GitHub/minishell/src/parser/tokeniser_helpers.c File Reference
tokeniser_helpers.c File Reference
#include "tokens.h"
Functions
t_token * new_token (char *value, t_token_type type)
void append_token (t_token **tokens, t_token *new_token)
Function Documentation
append_token()
void append_token (t_token ** tokens, t_token * new_token)
Definition at line 33 of file tokeniser_helpers.c.
{
    t_token *prev;
    if (!*tokens)
        *tokens = new_token;
    else
    {
        prev = *tokens;
        while (prev->next)
            prev = prev->next;
        prev->next = new_token;
    }
}
References new_token(), and s_token::next.
Referenced by append_phrase_if_valid(), and handle_special_chars().
new_token()
t_token * new_token (char * value, t_token_type type)
Definition at line 15 of file tokeniser_helpers.c.
{
    t_token *token;
    token = malloc(sizeof(t_token));
    if (!token)
        return (NULL);
    token->data = ft_strdup(value);
    if (!token->data)
    {
        free(token);
        return (NULL);
    }
    token->type = type;
    token->next = NULL;
    return (token);
}
References s_token::data, ft_strdup(), s_token::next, and s_token::type.
Referenced by append_phrase_if_valid(), append_token(), and handle_special_chars().