maxishell: /Users/dimadem/Documents/GitHub/minishell/inc/tokens.h File Reference
tokens.h File Reference
#include "../lib/libft/inc/libft.h"
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <readline/readline.h>
#include <readline/history.h>
#include <pwd.h>
#include "shell.h"
#include "env.h"
Classes
struct s_token
struct s_ast
struct s_loop_data
Macros
#define HISTORY_PATH "./utils/.maxishell_history"
Typedefs
typedef enum e_token_type t_token_type
typedef struct s_token t_token
typedef struct s_ast t_ast
typedef struct s_loop_data t_loop_data
Enumerations
enum e_token_type {
PHRASE , PIPE , ENV_VAR , REDIR_IN ,
REDIR_OUT , REDIR_APPEND , REDIR_HEREDOC
}
Functions
void add_node (t_token **head, char *str)
void print_stack (t_token **stack)
void free_stack (t_token **stack)
int calc_stack_size (t_token *stack)
char ** list_to_array (t_token *head)
void build_linked_list (t_token **tokens, char **argv)
void handle_quotes (char **tokens, int *pos, char **input)
void handle_special_chars (char **str, t_token **tokens)
void handle_regular_chars (char **tokens, int *pos, char **input, char *delim)
void skip_delimiters (char **input, char *delim)
void reallocate_tokens (char ***tokens, int *bufsize)
void parse_loop (char **input, char **tokens, int *pos, int *bufsize)
char ** parse_input (char *input)
char * generate_prompt (t_ms_data *data)
void make_history (char *line)
void loop_cleanup (char *line, t_token *tokens, char *prompt, t_ast *tree)
void free_ms_data (t_ms_data *data)
char * check_heredoc (char *line)
char * heredoc (char *eof)
void init_ms_data (t_ms_data *data, char **envp)
void initialise (int argc, char **argv)
void execute_command (char **parsed_text, t_token **tokens)
void print_maxishell (void)
int input_error_checks (const char *str)
t_token * tokenise (char *str)
void print_tokens (t_token *tokens)
t_ast * parse_tokens (t_token **tokens)
void visualize_ast (t_ast *root)
void free_ast (t_ast *node)
void free_all_tokens (t_token *tokens)
t_token * new_token (char *value, t_token_type type)
void append_token (t_token **tokens, t_token *new_token)
int valid_operator (const char **str)
t_ast * new_ast_node (t_token_type type)
t_ast * create_redir (t_token **tokens, t_token *tmp)
int arg_len (t_token *current)
void set_command_args (t_ast *command_node, t_token **tokens, int arg_count)
t_ast * manage_commands (t_token **tokens)
t_ast * create_redir_node (t_token *token)
int is_redir_node (t_token *tokens)
t_ast * manage_redirs (t_token **tokens)
t_ast * manage_pipe (t_token **tokens)
char * trim_input (char *str)
void print_ast_root (t_ast *root)
void execute_tree (t_ast *node, t_ms_data *data)
Macro Definition Documentation
HISTORY_PATH
#define HISTORY_PATH "./utils/.maxishell_history"
Definition at line 27 of file tokens.h.
Referenced by initialise(), and make_history().
Typedef Documentation
t_ast
typedef struct s_ast t_ast
t_loop_data
typedef struct s_loop_data t_loop_data
t_token
typedef struct s_token t_token
t_token_type
typedef enum e_token_type t_token_type
Enumeration Type Documentation
e_token_type
enum e_token_type
Enumerator
PHRASE
PIPE
ENV_VAR
REDIR_IN
REDIR_OUT
REDIR_APPEND
REDIR_HEREDOC
Definition at line 29 of file tokens.h.
{
    PHRASE,
    PIPE,
    ENV_VAR,
    REDIR_IN,
    REDIR_OUT,
    REDIR_APPEND,
    REDIR_HEREDOC
}   t_token_type;
Function Documentation
add_node()
void add_node (t_token ** head, char * str)
Definition at line 15 of file stack_control.c.
{
    t_token *new_node;
    t_token *curr_node;
    new_node = (t_token *)malloc(sizeof(t_token));
    if (!new_node)
        return ;
    new_node->data = str;
    new_node->next = NULL;
    if (*head == NULL)
    {
        *head = new_node;
        return ;
    }
    curr_node = *head;
    while (curr_node->next != NULL)
        curr_node = curr_node->next;
    curr_node->next = new_node;
}
References s_token::data, and s_token::next.
Referenced by build_linked_list().
append_token()
void append_token (t_token ** tokens, t_token * new_token)
Definition at line 33 of file tokeniser_helpers.c.
{
    t_token *prev;
    if (!*tokens)
        *tokens = new_token;
    else
    {
        prev = *tokens;
        while (prev->next)
            prev = prev->next;
        prev->next = new_token;
    }
}
References new_token(), and s_token::next.
Referenced by append_phrase_if_valid(), and handle_special_chars().
arg_len()
int arg_len (t_token * current)
Definition at line 48 of file parser_helpers.c.
{
    int arg_count;
    arg_count = 0;
    while (current && current->type == PHRASE)
    {
        arg_count++;
        current = current->next;
    }
    return (arg_count);
}
References s_token::next, PHRASE, and s_token::type.
Referenced by manage_commands().
build_linked_list()
void build_linked_list (t_token ** tokens, char ** argv)
Definition at line 15 of file stack_control_2.c.
{
    int i;
    i = 0;
    while (argv[i])
    {
        add_node(tokens, argv[i]);
        i++;
    }
}
References add_node().
calc_stack_size()
int calc_stack_size (t_token * stack)
Definition at line 65 of file stack_control.c.
{
    int         size;
    t_token     *current;
    size = 0;
    current = stack;
    while (current != NULL)
    {
        size++;
        current = current->next;
    }
    return (size);
}
References s_token::next.
Referenced by list_to_array().
check_heredoc()
char * check_heredoc (char * line)
Definition at line 15 of file heredoc.c.
{
    char    **parsed;
    parsed = ft_split(line, ' ');
    if (!ft_strcmp(parsed[0], "cat") && !ft_strcmp(parsed[1], "<<"))
        return (heredoc("EOF"));
    else
        return (line);
}
References ft_split(), ft_strcmp(), and heredoc().
create_redir()
t_ast * create_redir (t_token ** tokens, t_token * tmp)
Definition at line 35 of file parser_helpers.c.
{
    t_ast   *redirect_node;
    redirect_node = new_ast_node((*tokens)->type);
    *tokens = (*tokens)->next->next;
    redirect_node->left = manage_redirs(tokens);
    redirect_node->right = create_redir_node(tmp->next);
    free(tmp->data);
    free(tmp);
    return (redirect_node);
}
References create_redir_node(), s_token::data, s_ast::left, manage_redirs(), new_ast_node(), s_token::next, and s_ast::right.
Referenced by manage_redirs().
create_redir_node()
t_ast * create_redir_node (t_token * token)
Definition at line 21 of file parser.c.
{
    t_ast           *node;
    node = malloc(sizeof(t_ast));
    if (!node)
        return (NULL);
    node->type = token->type;
    node->args = malloc(sizeof(char *) * 2);
    if (!node->args)
    {
        free(node);
        return (NULL);
    }
    node->args[0] = token->data;
    node->args[1] = NULL;
    node->left = NULL;
    node->right = NULL;
    free(token);
    return (node);
}
References s_ast::args, s_token::data, s_ast::left, s_ast::right, s_ast::type, and s_token::type.
Referenced by clr_node(), and create_redir().
execute_command()
void execute_command (char ** parsed_text, t_token ** tokens)
execute_tree()
void execute_tree (t_ast * node, t_ms_data * data)
free_all_tokens()
void free_all_tokens (t_token * tokens)
Definition at line 16 of file clean_tree.c.
{
    t_token *temp;
    while (tokens)
    {
        temp = tokens;
        tokens = tokens->next;
        if (temp)
        {
            if (temp->data)
            {
                free(temp->data);
                temp->data = NULL;
            }
        }
        free(temp);
        temp = NULL;
    }
}
References s_token::data, and s_token::next.
free_ast()
void free_ast (t_ast * node)
Definition at line 37 of file clean_tree.c.
{
    int             i;
    i = 0;
    if (!node)
        return ;
    if (node->type == PHRASE && node->args)
    {
        while (node->args && node->args[i])
        {
            free(node->args[i]);
            i++;
        }
        free(node->args);
    }
    free_ast(node->left);
    free_ast(node->right);
    free(node);
}
References s_ast::args, free_ast(), s_ast::left, PHRASE, s_ast::right, and s_ast::type.
Referenced by free_ast(), and loop_cleanup().
free_ms_data()
void free_ms_data (t_ms_data * data)
Definition at line 43 of file clean_general.c.
{
    if (data)
    {
        free_args(data->args);
        free_env_list(data->envp);
        free_env_list(data->local_env);
        free(data->current_dir);
        free(data);
    }
}
References s_ms_data::args, s_ms_data::current_dir, s_ms_data::envp, free_args(), free_env_list(), and s_ms_data::local_env.
Referenced by main().
free_stack()
void free_stack (t_token ** stack)
Definition at line 51 of file stack_control.c.
{
    t_token *current;
    t_token *next;
    current = *stack;
    while (current != NULL)
    {
        next = current->next;
        free(current);
        current = next;
    }
}
References s_token::next.
generate_prompt()
char * generate_prompt (t_ms_data * data)
Definition at line 31 of file prompt.c.
{
    char    *prompt;
    size_t  prompt_len;
    if (data->std_in == -1)
        prompt_len = ft_strlen("minishell:~> ") + 1;
    else
        prompt_len = ft_strlen("> ") + 1;
    prompt = (char *)malloc(prompt_len);
    if (!prompt)
        exit(EXIT_FAILURE);
    if (data->std_in == -1)
        ft_strcpy(prompt, "minishell:~> ");
    else
        ft_strcpy(prompt, "> ");
    return (prompt);
}
References ft_strcpy(), ft_strlen(), and s_ms_data::std_in.
Referenced by main_loop().
handle_quotes()
void handle_quotes (char ** tokens, int * pos, char ** input)
handle_regular_chars()
void handle_regular_chars (char ** tokens, int * pos, char ** input, char * delim)
handle_special_chars()
void handle_special_chars (char ** str, t_token ** tokens)
Definition at line 22 of file tokeniser.c.
{
    if (**str == '<')
    {
        if (*(*str + 1) == '<')
        {
            append_token(tokens, new_token("<<", REDIR_HEREDOC));
            (*str)++;
        }
        else
            append_token(tokens, new_token("<", REDIR_IN));
    }
    else if (**str == '>')
    {
        if (*(*str + 1) == '>')
        {
            append_token(tokens, new_token(">>", REDIR_APPEND));
            (*str)++;
        }
        else
            append_token(tokens, new_token(">", REDIR_OUT));
    }
    else if (**str == '|')
        append_token(tokens, new_token("|", PIPE));
    (*str)++;
}
References append_token(), new_token(), PIPE, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, and REDIR_OUT.
Referenced by tokenise().
heredoc()
char * heredoc (char * eof)
Definition at line 26 of file heredoc.c.
{
    char    *line;
    char    *comb;
    comb = "";
    while (1)
    {
        line = readline("heredoc>");
        if (!ft_strcmp(line, eof))
            return (comb);
        comb = ft_strjoin(ft_strjoin(comb, line), "\n");
        free(line);
    }
}
References ft_strcmp(), and ft_strjoin().
Referenced by check_heredoc().
init_ms_data()
void init_ms_data (t_ms_data * data, char ** envp)
Definition at line 16 of file initialise.c.
{
    data->args = NULL;
    data->envp = NULL;
    init_env(&data->envp, envp);
    data->local_env = NULL;
    data->current_dir = getcwd(NULL, 0);
    data->exit_status = 0;
    data->std_in = -1;
    data->std_out = -1;
    data->std_err = 2;
}
References s_ms_data::args, s_ms_data::current_dir, s_ms_data::envp, s_ms_data::exit_status, init_env(), s_ms_data::local_env, s_ms_data::std_err, s_ms_data::std_in, and s_ms_data::std_out.
Referenced by main().
initialise()
void initialise (int argc, char ** argv)
Definition at line 29 of file initialise.c.
{
    if (argc > 1)
    {
        printf("Usage: %s\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    read_history(HISTORY_PATH);
}
References HISTORY_PATH.
Referenced by main().
input_error_checks()
int input_error_checks (const char * str)
Definition at line 99 of file input_checker.c.
{
    if (check_redirections(str))
        ft_printf("Input error: invalid redirection.\n");
    else if (check_operators(str))
        ft_printf("Input error: invalid operator.\n");
    else if (check_open_quotes(str))
        ft_printf("Input error: open quote.\n");
    else
        return (0);
    return (1);
}
References check_open_quotes(), check_operators(), check_redirections(), and ft_printf().
Referenced by main_loop().
is_redir_node()
int is_redir_node (t_token * tokens)
Definition at line 43 of file parser.c.
{
    if (tokens->type == REDIR_IN
        || tokens->type == REDIR_OUT
        || tokens->type == REDIR_APPEND
        || tokens->type == REDIR_HEREDOC)
        return (1);
    return (0);
}
References REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, REDIR_OUT, and s_token::type.
Referenced by manage_redirs().
list_to_array()
char ** list_to_array (t_token * head)
Definition at line 80 of file stack_control.c.
{
    int         count;
    int         i;
    char        **arr;
    t_token     *current;
    current = head;
    count = calc_stack_size(current);
    arr = (char **)malloc((count + 1) * sizeof(char *));
    if (!arr)
        return (NULL);
    current = head;
    i = 0;
    while (i < count)
    {
        arr[i] = ft_strdup(current->data);
        current = current->next;
        i++;
    }
    arr[count] = NULL;
    return (arr);
}
References calc_stack_size(), s_token::data, ft_strdup(), and s_token::next.
loop_cleanup()
void loop_cleanup (char * line, t_token * tokens, char * prompt, t_ast * tree)
Definition at line 55 of file clean_general.c.
{
    free(line);
    free(prompt);
    (void)tokens;
    free_ast(tree);
}
References free_ast().
Referenced by main_loop(), and status_handler().
make_history()
void make_history (char * line)
Definition at line 15 of file aux.c.
{
    printf("line: %s\n", line);
    if (*line)
        add_history(line);
    write_history(HISTORY_PATH);
}
References HISTORY_PATH.
Referenced by main_loop().
manage_commands()
t_ast * manage_commands (t_token ** tokens)
Definition at line 80 of file parser_helpers.c.
{
    t_ast       *command_node;
    int         arg_count;
    command_node = new_ast_node(PHRASE);
    arg_count = arg_len(*tokens);
    command_node->args = malloc(sizeof(char *) * (arg_count + 1));
    if (!command_node->args)
        return (NULL);
    set_command_args(command_node, tokens, arg_count);
    return (command_node);
}
References arg_len(), s_ast::args, new_ast_node(), PHRASE, and set_command_args().
Referenced by manage_redirs().
manage_pipe()
t_ast * manage_pipe (t_token ** tokens)
Definition at line 87 of file parser.c.
{
    t_token     *tmp;
    t_token     *next_token;
    t_ast       *pipe_node;
    tmp = *tokens;
    while (*tokens && (*tokens)->next)
    {
        next_token = (*tokens)->next;
        if ((*tokens)->next->type == PIPE)
        {
            pipe_node = new_ast_node((*tokens)->next->type);
            (*tokens)->next = NULL;
            pipe_node->left = manage_redirs(&tmp);
            if (next_token->next == NULL)
                pipe_node->right = NULL;
            else
                pipe_node->right = manage_pipe(&(next_token->next));
            free(next_token->data);
            free(next_token);
            return (pipe_node);
        }
        *tokens = next_token;
    }
    return (manage_redirs(&tmp));
}
References s_token::data, s_ast::left, manage_pipe(), manage_redirs(), new_ast_node(), s_token::next, PIPE, and s_ast::right.
Referenced by manage_pipe(), and parse_tokens().
manage_redirs()
t_ast * manage_redirs (t_token ** tokens)
Definition at line 63 of file parser.c.
{
    t_token     *tmp;
    t_ast       *redirect_node;
    t_token     *next_token;
    if (!*tokens)
        return (NULL);
    tmp = *tokens;
    if (is_redir_node(*tokens))
        return (create_redir(tokens, tmp));
    while (*tokens && (*tokens)->next)
    {
        next_token = (*tokens)->next;
        if (is_redir_node((*tokens)->next))
        {
            redirect_node = new_ast_node((*tokens)->next->type);
            return (clr_node(tokens, next_token, redirect_node));
        }
        *tokens = next_token;
    }
    return (manage_commands(&tmp));
}
References clr_node(), create_redir(), is_redir_node(), manage_commands(), new_ast_node(), and s_token::next.
Referenced by clr_node(), create_redir(), and manage_pipe().
new_ast_node()
t_ast * new_ast_node (t_token_type type)
Definition at line 21 of file parser_helpers.c.
{
    t_ast       *node;
    node = malloc(sizeof(t_ast));
    if (!node)
        return (NULL);
    node->type = type;
    node->args = NULL;
    node->left = NULL;
    node->right = NULL;
    return (node);
}
References s_ast::args, s_ast::left, s_ast::right, and s_ast::type.
Referenced by create_redir(), manage_commands(), manage_pipe(), and manage_redirs().
new_token()
t_token * new_token (char * value, t_token_type type)
Definition at line 15 of file tokeniser_helpers.c.
{
    t_token *token;
    token = malloc(sizeof(t_token));
    if (!token)
        return (NULL);
    token->data = ft_strdup(value);
    if (!token->data)
    {
        free(token);
        return (NULL);
    }
    token->type = type;
    token->next = NULL;
    return (token);
}
References s_token::data, ft_strdup(), s_token::next, and s_token::type.
Referenced by append_phrase_if_valid(), append_token(), and handle_special_chars().
parse_input()
char ** parse_input (char * input)
parse_loop()
void parse_loop (char ** input, char ** tokens, int * pos, int * bufsize)
parse_tokens()
t_ast * parse_tokens (t_token ** tokens)
Definition at line 17 of file parser_utils.c.
{
    if (!tokens || !*tokens)
        return (NULL);
    return (manage_pipe(tokens));
}
References manage_pipe().
Referenced by main_loop().
print_ast_root()
void print_ast_root (t_ast * root)
Definition at line 103 of file visualiser.c.
{
    print_ast_graphical(root, 0, "", 0);
}
References print_ast_graphical().
Referenced by main_loop().
print_maxishell()
void print_maxishell (void)
Definition at line 69 of file prompt.c.
{
    ft_printf("\033[1;33m\n\n\n\n\n");
    ft_printf(""
        "\n");
    ft_printf(""
        "\n");
    ft_printf(""
        "\n");
    ft_printf(""
        "\n");
    ft_printf(""
        "\n");
    ft_printf(""
        "\n");
    ft_printf("\n");
    ft_printf("            \033[1;34m"
        "Version 0.0.0\033[0m\n");
    ft_printf("           \033[1;36m"
        "By   \033[0m\n");
    ft_printf("\n");
}
References ft_printf().
Referenced by main().
print_stack()
void print_stack (t_token ** stack)
Definition at line 36 of file stack_control.c.
{
    t_token *current_node;
    int     i;
    i = 0;
    current_node = *stack;
    while (current_node != NULL)
    {
        ft_printf("input[%d] ->  %s \n", i, current_node->data);
        current_node = current_node->next;
        i++;
    }
}
References s_token::data, ft_printf(), and s_token::next.
print_tokens()
void print_tokens (t_token * tokens)
Definition at line 91 of file tokeniser.c.
{
    t_token *token;
    int     i;
    i = 0;
    token = tokens;
    while (token != NULL)
    {
        printf("input[%d] ->  %s \n", i, token->data);
        token = token->next;
        i++;
    }
}
References s_token::data, and s_token::next.
reallocate_tokens()
void reallocate_tokens (char *** tokens, int * bufsize)
set_command_args()
void set_command_args (t_ast * command_node, t_token ** tokens, int arg_count)
Definition at line 61 of file parser_helpers.c.
{
    int     i;
    t_token *tmp;
    i = 0;
    while (i < arg_count)
    {
        command_node->args[i] = ft_strdup((*tokens)->data);
        tmp = *tokens;
        *tokens = (*tokens)->next;
        free(tmp->data);
        free(tmp);
        i++;
    }
    command_node->args[arg_count] = NULL;
}
References s_ast::args, s_token::data, ft_strdup(), and s_token::next.
Referenced by manage_commands().
skip_delimiters()
void skip_delimiters (char ** input, char * delim)
tokenise()
t_token * tokenise (char * str)
Definition at line 106 of file tokeniser.c.
{
    t_token *tokens;
    tokens = NULL;
    while (*str)
    {
        while (*str && ft_strchr(" \t\n\r\v\f", *str) != NULL)
            str++;
        if (ft_strchr("<|>", *str) != NULL)
            handle_special_chars(&str, &tokens);
        else
            handle_phrase(&str, &tokens);
    }
    return (tokens);
}
References ft_strchr(), handle_phrase(), and handle_special_chars().
Referenced by main_loop().
trim_input()
char * trim_input (char * str)
Definition at line 15 of file input_checker_helpers.c.
{
    char    *trimmed_str;
    trimmed_str = ft_strtrim(str, " \t\n\r\v\f");
    if (!trimmed_str)
        return (0);
    return (trimmed_str);
}
References ft_strtrim().
Referenced by main_loop().
valid_operator()
int valid_operator (const char ** str)
Definition at line 25 of file input_checker_helpers.c.
{
    const char  *start;
    start = (*str)++;
    if (*start == **str)
        (*str)++;
    *str = ft_exclude_delimiters(*str, " \t\n\r\v\f");
    if (**str == '<' || **str == '>' || **str == '|' || **str == '\0')
        return (0);
    return (1);
}
References ft_exclude_delimiters().
Referenced by check_redirections().
visualize_ast()
void visualize_ast (t_ast * root)