maxishell: /Users/dimadem/Documents/GitHub/minishell/src/builtins/unset.c File Reference
unset.c File Reference
#include "shell.h"
#include "env.h"
#include "libft.h"
#include <unistd.h>
Functions
int builtin_unset (t_ms_data *data)
Function Documentation
builtin_unset()
int builtin_unset (t_ms_data * data)
Definition at line 26 of file unset.c.
{
    int i;
    int ret;
    i = 0;
    ret = 0;
    while (data->args[++i])
    {
        if (unset_env(&data->envp, data->args[i]) == -1)
        {
            ft_putstr_fd("bash: unset: `", STDERR_FILENO);
            ft_putstr_fd(data->args[i], STDERR_FILENO);
            ft_putendl_fd("': not a valid identifier", STDERR_FILENO);
            ret = 1;
        }
    }
    data->exit_status = ret;
    return (ret);
}
References s_ms_data::args, s_ms_data::envp, s_ms_data::exit_status, ft_putendl_fd(), ft_putstr_fd(), and unset_env().
Referenced by execute().